-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretClassifier_xgbTree
-- Dataset : BinaryClass_10
-- Database : monetdb


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH "DT_node_lookup" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.0344060585) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.34117651 AS "Score" UNION ALL SELECT 2 AS nid, -0.470270306 AS "Score") AS "Values"), 
"DT_Output" AS 
(SELECT "DT_node_lookup"."KEY" AS "KEY", "DT_node_lookup".node_id_2 AS node_id_2, "DT_node_data".nid AS nid, "DT_node_data"."Score" AS "Score" 
FROM "DT_node_lookup" LEFT OUTER JOIN "DT_node_data" ON "DT_node_lookup".node_id_2 = "DT_node_data".nid), 
"XGB_Model_0_0" AS 
(SELECT "DT_Output"."KEY" AS "KEY", "DT_Output"."Score" AS "Score_0" 
FROM "DT_Output"), 
"DT_node_lookup_1" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.0344060585) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_1" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.254449219 AS "Score" UNION ALL SELECT 2 AS nid, -0.364018798 AS "Score") AS "Values"), 
"DT_Output_1" AS 
(SELECT "DT_node_lookup_1"."KEY" AS "KEY", "DT_node_lookup_1".node_id_2 AS node_id_2, "DT_node_data_1".nid AS nid, "DT_node_data_1"."Score" AS "Score" 
FROM "DT_node_lookup_1" LEFT OUTER JOIN "DT_node_data_1" ON "DT_node_lookup_1".node_id_2 = "DT_node_data_1".nid), 
"XGB_Model_0_1" AS 
(SELECT "DT_Output_1"."KEY" AS "KEY", "DT_Output_1"."Score" AS "Score_0" 
FROM "DT_Output_1"), 
"DT_node_lookup_2" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < -0.272910357) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_2" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.223831549 AS "Score" UNION ALL SELECT 2 AS nid, -0.270444721 AS "Score") AS "Values"), 
"DT_Output_2" AS 
(SELECT "DT_node_lookup_2"."KEY" AS "KEY", "DT_node_lookup_2".node_id_2 AS node_id_2, "DT_node_data_2".nid AS nid, "DT_node_data_2"."Score" AS "Score" 
FROM "DT_node_lookup_2" LEFT OUTER JOIN "DT_node_data_2" ON "DT_node_lookup_2".node_id_2 = "DT_node_data_2".nid), 
"XGB_Model_0_2" AS 
(SELECT "DT_Output_2"."KEY" AS "KEY", "DT_Output_2"."Score" AS "Score_0" 
FROM "DT_Output_2"), 
"DT_node_lookup_3" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_3" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.176409557 AS "Score" UNION ALL SELECT 2 AS nid, 0.35873875 AS "Score") AS "Values"), 
"DT_Output_3" AS 
(SELECT "DT_node_lookup_3"."KEY" AS "KEY", "DT_node_lookup_3".node_id_2 AS node_id_2, "DT_node_data_3".nid AS nid, "DT_node_data_3"."Score" AS "Score" 
FROM "DT_node_lookup_3" LEFT OUTER JOIN "DT_node_data_3" ON "DT_node_lookup_3".node_id_2 = "DT_node_data_3".nid), 
"XGB_Model_0_3" AS 
(SELECT "DT_Output_3"."KEY" AS "KEY", "DT_Output_3"."Score" AS "Score_0" 
FROM "DT_Output_3"), 
"DT_node_lookup_4" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_4" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.13117902 AS "Score" UNION ALL SELECT 2 AS nid, 0.316008687 AS "Score") AS "Values"), 
"DT_Output_4" AS 
(SELECT "DT_node_lookup_4"."KEY" AS "KEY", "DT_node_lookup_4".node_id_2 AS node_id_2, "DT_node_data_4".nid AS nid, "DT_node_data_4"."Score" AS "Score" 
FROM "DT_node_lookup_4" LEFT OUTER JOIN "DT_node_data_4" ON "DT_node_lookup_4".node_id_2 = "DT_node_data_4".nid), 
"XGB_Model_0_4" AS 
(SELECT "DT_Output_4"."KEY" AS "KEY", "DT_Output_4"."Score" AS "Score_0" 
FROM "DT_Output_4"), 
"DT_node_lookup_5" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < -0.236128673) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_5" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.286464542 AS "Score" UNION ALL SELECT 2 AS nid, 0.111267611 AS "Score") AS "Values"), 
"DT_Output_5" AS 
(SELECT "DT_node_lookup_5"."KEY" AS "KEY", "DT_node_lookup_5".node_id_2 AS node_id_2, "DT_node_data_5".nid AS nid, "DT_node_data_5"."Score" AS "Score" 
FROM "DT_node_lookup_5" LEFT OUTER JOIN "DT_node_data_5" ON "DT_node_lookup_5".node_id_2 = "DT_node_data_5".nid), 
"XGB_Model_0_5" AS 
(SELECT "DT_Output_5"."KEY" AS "KEY", "DT_Output_5"."Score" AS "Score_0" 
FROM "DT_Output_5"), 
"DT_node_lookup_6" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -1.15499079) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_6" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.262074739 AS "Score" UNION ALL SELECT 2 AS nid, 0.110886045 AS "Score") AS "Values"), 
"DT_Output_6" AS 
(SELECT "DT_node_lookup_6"."KEY" AS "KEY", "DT_node_lookup_6".node_id_2 AS node_id_2, "DT_node_data_6".nid AS nid, "DT_node_data_6"."Score" AS "Score" 
FROM "DT_node_lookup_6" LEFT OUTER JOIN "DT_node_data_6" ON "DT_node_lookup_6".node_id_2 = "DT_node_data_6".nid), 
"XGB_Model_0_6" AS 
(SELECT "DT_Output_6"."KEY" AS "KEY", "DT_Output_6"."Score" AS "Score_0" 
FROM "DT_Output_6"), 
"DT_node_lookup_7" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_7" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.106741302 AS "Score" UNION ALL SELECT 2 AS nid, 0.276592612 AS "Score") AS "Values"), 
"DT_Output_7" AS 
(SELECT "DT_node_lookup_7"."KEY" AS "KEY", "DT_node_lookup_7".node_id_2 AS node_id_2, "DT_node_data_7".nid AS nid, "DT_node_data_7"."Score" AS "Score" 
FROM "DT_node_lookup_7" LEFT OUTER JOIN "DT_node_data_7" ON "DT_node_lookup_7".node_id_2 = "DT_node_data_7".nid), 
"XGB_Model_0_7" AS 
(SELECT "DT_Output_7"."KEY" AS "KEY", "DT_Output_7"."Score" AS "Score_0" 
FROM "DT_Output_7"), 
"DT_node_lookup_8" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.437053055) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_8" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.100927971 AS "Score" UNION ALL SELECT 2 AS nid, -0.265338153 AS "Score") AS "Values"), 
"DT_Output_8" AS 
(SELECT "DT_node_lookup_8"."KEY" AS "KEY", "DT_node_lookup_8".node_id_2 AS node_id_2, "DT_node_data_8".nid AS nid, "DT_node_data_8"."Score" AS "Score" 
FROM "DT_node_lookup_8" LEFT OUTER JOIN "DT_node_data_8" ON "DT_node_lookup_8".node_id_2 = "DT_node_data_8".nid), 
"XGB_Model_0_8" AS 
(SELECT "DT_Output_8"."KEY" AS "KEY", "DT_Output_8"."Score" AS "Score_0" 
FROM "DT_Output_8"), 
"DT_node_lookup_9" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_9" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.216065422 AS "Score" UNION ALL SELECT 2 AS nid, 0.107111029 AS "Score") AS "Values"), 
"DT_Output_9" AS 
(SELECT "DT_node_lookup_9"."KEY" AS "KEY", "DT_node_lookup_9".node_id_2 AS node_id_2, "DT_node_data_9".nid AS nid, "DT_node_data_9"."Score" AS "Score" 
FROM "DT_node_lookup_9" LEFT OUTER JOIN "DT_node_data_9" ON "DT_node_lookup_9".node_id_2 = "DT_node_data_9".nid), 
"XGB_Model_0_9" AS 
(SELECT "DT_Output_9"."KEY" AS "KEY", "DT_Output_9"."Score" AS "Score_0" 
FROM "DT_Output_9"), 
"XGB_0" AS 
(SELECT "XGB_esu_0"."KEY" AS "KEY", "XGB_esu_0"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_Model_0_0"."KEY" AS "KEY", CAST("XGB_Model_0_0"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_0" UNION ALL SELECT "XGB_Model_0_1"."KEY" AS "KEY", CAST("XGB_Model_0_1"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_1" UNION ALL SELECT "XGB_Model_0_2"."KEY" AS "KEY", CAST("XGB_Model_0_2"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_2" UNION ALL SELECT "XGB_Model_0_3"."KEY" AS "KEY", CAST("XGB_Model_0_3"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_3" UNION ALL SELECT "XGB_Model_0_4"."KEY" AS "KEY", CAST("XGB_Model_0_4"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_4" UNION ALL SELECT "XGB_Model_0_5"."KEY" AS "KEY", CAST("XGB_Model_0_5"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_5" UNION ALL SELECT "XGB_Model_0_6"."KEY" AS "KEY", CAST("XGB_Model_0_6"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_6" UNION ALL SELECT "XGB_Model_0_7"."KEY" AS "KEY", CAST("XGB_Model_0_7"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_7" UNION ALL SELECT "XGB_Model_0_8"."KEY" AS "KEY", CAST("XGB_Model_0_8"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_8" UNION ALL SELECT "XGB_Model_0_9"."KEY" AS "KEY", CAST("XGB_Model_0_9"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_9") AS "XGB_esu_0"), 
"DT_node_lookup_10" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_10" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0893263817 AS "Score" UNION ALL SELECT 2 AS nid, 0.249421999 AS "Score") AS "Values"), 
"DT_Output_10" AS 
(SELECT "DT_node_lookup_10"."KEY" AS "KEY", "DT_node_lookup_10".node_id_2 AS node_id_2, "DT_node_data_10".nid AS nid, "DT_node_data_10"."Score" AS "Score" 
FROM "DT_node_lookup_10" LEFT OUTER JOIN "DT_node_data_10" ON "DT_node_lookup_10".node_id_2 = "DT_node_data_10".nid), 
"XGB_Model_0_10" AS 
(SELECT "DT_Output_10"."KEY" AS "KEY", "DT_Output_10"."Score" AS "Score_0" 
FROM "DT_Output_10"), 
"DT_node_lookup_11" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < -0.236128673) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_11" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.232047617 AS "Score" UNION ALL SELECT 2 AS nid, 0.0726631656 AS "Score") AS "Values"), 
"DT_Output_11" AS 
(SELECT "DT_node_lookup_11"."KEY" AS "KEY", "DT_node_lookup_11".node_id_2 AS node_id_2, "DT_node_data_11".nid AS nid, "DT_node_data_11"."Score" AS "Score" 
FROM "DT_node_lookup_11" LEFT OUTER JOIN "DT_node_data_11" ON "DT_node_lookup_11".node_id_2 = "DT_node_data_11".nid), 
"XGB_Model_0_11" AS 
(SELECT "DT_Output_11"."KEY" AS "KEY", "DT_Output_11"."Score" AS "Score_0" 
FROM "DT_Output_11"), 
"DT_node_lookup_12" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -1.15499079) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_12" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.207511723 AS "Score" UNION ALL SELECT 2 AS nid, 0.0891588777 AS "Score") AS "Values"), 
"DT_Output_12" AS 
(SELECT "DT_node_lookup_12"."KEY" AS "KEY", "DT_node_lookup_12".node_id_2 AS node_id_2, "DT_node_data_12".nid AS nid, "DT_node_data_12"."Score" AS "Score" 
FROM "DT_node_lookup_12" LEFT OUTER JOIN "DT_node_data_12" ON "DT_node_lookup_12".node_id_2 = "DT_node_data_12".nid), 
"XGB_Model_0_12" AS 
(SELECT "DT_Output_12"."KEY" AS "KEY", "DT_Output_12"."Score" AS "Score_0" 
FROM "DT_Output_12"), 
"DT_node_lookup_13" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_4" < 1.25147688) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_13" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.064687416 AS "Score" UNION ALL SELECT 2 AS nid, 0.285560012 AS "Score") AS "Values"), 
"DT_Output_13" AS 
(SELECT "DT_node_lookup_13"."KEY" AS "KEY", "DT_node_lookup_13".node_id_2 AS node_id_2, "DT_node_data_13".nid AS nid, "DT_node_data_13"."Score" AS "Score" 
FROM "DT_node_lookup_13" LEFT OUTER JOIN "DT_node_data_13" ON "DT_node_lookup_13".node_id_2 = "DT_node_data_13".nid), 
"XGB_Model_0_13" AS 
(SELECT "DT_Output_13"."KEY" AS "KEY", "DT_Output_13"."Score" AS "Score_0" 
FROM "DT_Output_13"), 
"DT_node_lookup_14" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.675393462) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_14" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.217537865 AS "Score" UNION ALL SELECT 2 AS nid, 0.0754143149 AS "Score") AS "Values"), 
"DT_Output_14" AS 
(SELECT "DT_node_lookup_14"."KEY" AS "KEY", "DT_node_lookup_14".node_id_2 AS node_id_2, "DT_node_data_14".nid AS nid, "DT_node_data_14"."Score" AS "Score" 
FROM "DT_node_lookup_14" LEFT OUTER JOIN "DT_node_data_14" ON "DT_node_lookup_14".node_id_2 = "DT_node_data_14".nid), 
"XGB_Model_0_14" AS 
(SELECT "DT_Output_14"."KEY" AS "KEY", "DT_Output_14"."Score" AS "Score_0" 
FROM "DT_Output_14"), 
"DT_node_lookup_15" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.437053055) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_15" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0666957349 AS "Score" UNION ALL SELECT 2 AS nid, -0.225432023 AS "Score") AS "Values"), 
"DT_Output_15" AS 
(SELECT "DT_node_lookup_15"."KEY" AS "KEY", "DT_node_lookup_15".node_id_2 AS node_id_2, "DT_node_data_15".nid AS nid, "DT_node_data_15"."Score" AS "Score" 
FROM "DT_node_lookup_15" LEFT OUTER JOIN "DT_node_data_15" ON "DT_node_lookup_15".node_id_2 = "DT_node_data_15".nid), 
"XGB_Model_0_15" AS 
(SELECT "DT_Output_15"."KEY" AS "KEY", "DT_Output_15"."Score" AS "Score_0" 
FROM "DT_Output_15"), 
"DT_node_lookup_16" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_16" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.166407958 AS "Score" UNION ALL SELECT 2 AS nid, 0.0815871432 AS "Score") AS "Values"), 
"DT_Output_16" AS 
(SELECT "DT_node_lookup_16"."KEY" AS "KEY", "DT_node_lookup_16".node_id_2 AS node_id_2, "DT_node_data_16".nid AS nid, "DT_node_data_16"."Score" AS "Score" 
FROM "DT_node_lookup_16" LEFT OUTER JOIN "DT_node_data_16" ON "DT_node_lookup_16".node_id_2 = "DT_node_data_16".nid), 
"XGB_Model_0_16" AS 
(SELECT "DT_Output_16"."KEY" AS "KEY", "DT_Output_16"."Score" AS "Score_0" 
FROM "DT_Output_16"), 
"DT_node_lookup_17" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_17" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0826590955 AS "Score" UNION ALL SELECT 2 AS nid, 0.229801178 AS "Score") AS "Values"), 
"DT_Output_17" AS 
(SELECT "DT_node_lookup_17"."KEY" AS "KEY", "DT_node_lookup_17".node_id_2 AS node_id_2, "DT_node_data_17".nid AS nid, "DT_node_data_17"."Score" AS "Score" 
FROM "DT_node_lookup_17" LEFT OUTER JOIN "DT_node_data_17" ON "DT_node_lookup_17".node_id_2 = "DT_node_data_17".nid), 
"XGB_Model_0_17" AS 
(SELECT "DT_Output_17"."KEY" AS "KEY", "DT_Output_17"."Score" AS "Score_0" 
FROM "DT_Output_17"), 
"DT_node_lookup_18" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_18" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0611410104 AS "Score" UNION ALL SELECT 2 AS nid, 0.210481361 AS "Score") AS "Values"), 
"DT_Output_18" AS 
(SELECT "DT_node_lookup_18"."KEY" AS "KEY", "DT_node_lookup_18".node_id_2 AS node_id_2, "DT_node_data_18".nid AS nid, "DT_node_data_18"."Score" AS "Score" 
FROM "DT_node_lookup_18" LEFT OUTER JOIN "DT_node_data_18" ON "DT_node_lookup_18".node_id_2 = "DT_node_data_18".nid), 
"XGB_Model_0_18" AS 
(SELECT "DT_Output_18"."KEY" AS "KEY", "DT_Output_18"."Score" AS "Score_0" 
FROM "DT_Output_18"), 
"DT_node_lookup_19" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.547154188) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_19" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.185743317 AS "Score" UNION ALL SELECT 2 AS nid, 0.0733267814 AS "Score") AS "Values"), 
"DT_Output_19" AS 
(SELECT "DT_node_lookup_19"."KEY" AS "KEY", "DT_node_lookup_19".node_id_2 AS node_id_2, "DT_node_data_19".nid AS nid, "DT_node_data_19"."Score" AS "Score" 
FROM "DT_node_lookup_19" LEFT OUTER JOIN "DT_node_data_19" ON "DT_node_lookup_19".node_id_2 = "DT_node_data_19".nid), 
"XGB_Model_0_19" AS 
(SELECT "DT_Output_19"."KEY" AS "KEY", "DT_Output_19"."Score" AS "Score_0" 
FROM "DT_Output_19"), 
"XGB_1" AS 
(SELECT "XGB_esu_1"."KEY" AS "KEY", "XGB_esu_1"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_Model_0_10"."KEY" AS "KEY", CAST("XGB_Model_0_10"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_10" UNION ALL SELECT "XGB_Model_0_11"."KEY" AS "KEY", CAST("XGB_Model_0_11"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_11" UNION ALL SELECT "XGB_Model_0_12"."KEY" AS "KEY", CAST("XGB_Model_0_12"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_12" UNION ALL SELECT "XGB_Model_0_13"."KEY" AS "KEY", CAST("XGB_Model_0_13"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_13" UNION ALL SELECT "XGB_Model_0_14"."KEY" AS "KEY", CAST("XGB_Model_0_14"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_14" UNION ALL SELECT "XGB_Model_0_15"."KEY" AS "KEY", CAST("XGB_Model_0_15"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_15" UNION ALL SELECT "XGB_Model_0_16"."KEY" AS "KEY", CAST("XGB_Model_0_16"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_16" UNION ALL SELECT "XGB_Model_0_17"."KEY" AS "KEY", CAST("XGB_Model_0_17"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_17" UNION ALL SELECT "XGB_Model_0_18"."KEY" AS "KEY", CAST("XGB_Model_0_18"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_18" UNION ALL SELECT "XGB_Model_0_19"."KEY" AS "KEY", CAST("XGB_Model_0_19"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_19") AS "XGB_esu_1"), 
"DT_node_lookup_20" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_20" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.160443842 AS "Score" UNION ALL SELECT 2 AS nid, 0.0837319717 AS "Score") AS "Values"), 
"DT_Output_20" AS 
(SELECT "DT_node_lookup_20"."KEY" AS "KEY", "DT_node_lookup_20".node_id_2 AS node_id_2, "DT_node_data_20".nid AS nid, "DT_node_data_20"."Score" AS "Score" 
FROM "DT_node_lookup_20" LEFT OUTER JOIN "DT_node_data_20" ON "DT_node_lookup_20".node_id_2 = "DT_node_data_20".nid), 
"XGB_Model_0_20" AS 
(SELECT "DT_Output_20"."KEY" AS "KEY", "DT_Output_20"."Score" AS "Score_0" 
FROM "DT_Output_20"), 
"DT_node_lookup_21" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_4" < 1.25147688) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_21" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0563599691 AS "Score" UNION ALL SELECT 2 AS nid, 0.23353155 AS "Score") AS "Values"), 
"DT_Output_21" AS 
(SELECT "DT_node_lookup_21"."KEY" AS "KEY", "DT_node_lookup_21".node_id_2 AS node_id_2, "DT_node_data_21".nid AS nid, "DT_node_data_21"."Score" AS "Score" 
FROM "DT_node_lookup_21" LEFT OUTER JOIN "DT_node_data_21" ON "DT_node_lookup_21".node_id_2 = "DT_node_data_21".nid), 
"XGB_Model_0_21" AS 
(SELECT "DT_Output_21"."KEY" AS "KEY", "DT_Output_21"."Score" AS "Score_0" 
FROM "DT_Output_21"), 
"DT_node_lookup_22" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.437053055) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_22" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.062875241 AS "Score" UNION ALL SELECT 2 AS nid, -0.201246262 AS "Score") AS "Values"), 
"DT_Output_22" AS 
(SELECT "DT_node_lookup_22"."KEY" AS "KEY", "DT_node_lookup_22".node_id_2 AS node_id_2, "DT_node_data_22".nid AS nid, "DT_node_data_22"."Score" AS "Score" 
FROM "DT_node_lookup_22" LEFT OUTER JOIN "DT_node_data_22" ON "DT_node_lookup_22".node_id_2 = "DT_node_data_22".nid), 
"XGB_Model_0_22" AS 
(SELECT "DT_Output_22"."KEY" AS "KEY", "DT_Output_22"."Score" AS "Score_0" 
FROM "DT_Output_22"), 
"DT_node_lookup_23" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.299286783) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_23" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0634181276 AS "Score" UNION ALL SELECT 2 AS nid, 0.175346553 AS "Score") AS "Values"), 
"DT_Output_23" AS 
(SELECT "DT_node_lookup_23"."KEY" AS "KEY", "DT_node_lookup_23".node_id_2 AS node_id_2, "DT_node_data_23".nid AS nid, "DT_node_data_23"."Score" AS "Score" 
FROM "DT_node_lookup_23" LEFT OUTER JOIN "DT_node_data_23" ON "DT_node_lookup_23".node_id_2 = "DT_node_data_23".nid), 
"XGB_Model_0_23" AS 
(SELECT "DT_Output_23"."KEY" AS "KEY", "DT_Output_23"."Score" AS "Score_0" 
FROM "DT_Output_23"), 
"DT_node_lookup_24" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_24" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.145116553 AS "Score" UNION ALL SELECT 2 AS nid, 0.0787810385 AS "Score") AS "Values"), 
"DT_Output_24" AS 
(SELECT "DT_node_lookup_24"."KEY" AS "KEY", "DT_node_lookup_24".node_id_2 AS node_id_2, "DT_node_data_24".nid AS nid, "DT_node_data_24"."Score" AS "Score" 
FROM "DT_node_lookup_24" LEFT OUTER JOIN "DT_node_data_24" ON "DT_node_lookup_24".node_id_2 = "DT_node_data_24".nid), 
"XGB_Model_0_24" AS 
(SELECT "DT_Output_24"."KEY" AS "KEY", "DT_Output_24"."Score" AS "Score_0" 
FROM "DT_Output_24"), 
"DT_node_lookup_25" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < 1.66039979) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_25" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0558705404 AS "Score" UNION ALL SELECT 2 AS nid, -0.198153749 AS "Score") AS "Values"), 
"DT_Output_25" AS 
(SELECT "DT_node_lookup_25"."KEY" AS "KEY", "DT_node_lookup_25".node_id_2 AS node_id_2, "DT_node_data_25".nid AS nid, "DT_node_data_25"."Score" AS "Score" 
FROM "DT_node_lookup_25" LEFT OUTER JOIN "DT_node_data_25" ON "DT_node_lookup_25".node_id_2 = "DT_node_data_25".nid), 
"XGB_Model_0_25" AS 
(SELECT "DT_Output_25"."KEY" AS "KEY", "DT_Output_25"."Score" AS "Score_0" 
FROM "DT_Output_25"), 
"DT_node_lookup_26" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.547154188) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_26" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.171179727 AS "Score" UNION ALL SELECT 2 AS nid, 0.0576509871 AS "Score") AS "Values"), 
"DT_Output_26" AS 
(SELECT "DT_node_lookup_26"."KEY" AS "KEY", "DT_node_lookup_26".node_id_2 AS node_id_2, "DT_node_data_26".nid AS nid, "DT_node_data_26"."Score" AS "Score" 
FROM "DT_node_lookup_26" LEFT OUTER JOIN "DT_node_data_26" ON "DT_node_lookup_26".node_id_2 = "DT_node_data_26".nid), 
"XGB_Model_0_26" AS 
(SELECT "DT_Output_26"."KEY" AS "KEY", "DT_Output_26"."Score" AS "Score_0" 
FROM "DT_Output_26"), 
"DT_node_lookup_27" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_4" < 1.25147688) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_27" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0544848479 AS "Score" UNION ALL SELECT 2 AS nid, 0.19554843 AS "Score") AS "Values"), 
"DT_Output_27" AS 
(SELECT "DT_node_lookup_27"."KEY" AS "KEY", "DT_node_lookup_27".node_id_2 AS node_id_2, "DT_node_data_27".nid AS nid, "DT_node_data_27"."Score" AS "Score" 
FROM "DT_node_lookup_27" LEFT OUTER JOIN "DT_node_data_27" ON "DT_node_lookup_27".node_id_2 = "DT_node_data_27".nid), 
"XGB_Model_0_27" AS 
(SELECT "DT_Output_27"."KEY" AS "KEY", "DT_Output_27"."Score" AS "Score_0" 
FROM "DT_Output_27"), 
"DT_node_lookup_28" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.299286783) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_28" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0563655421 AS "Score" UNION ALL SELECT 2 AS nid, 0.167490408 AS "Score") AS "Values"), 
"DT_Output_28" AS 
(SELECT "DT_node_lookup_28"."KEY" AS "KEY", "DT_node_lookup_28".node_id_2 AS node_id_2, "DT_node_data_28".nid AS nid, "DT_node_data_28"."Score" AS "Score" 
FROM "DT_node_lookup_28" LEFT OUTER JOIN "DT_node_data_28" ON "DT_node_lookup_28".node_id_2 = "DT_node_data_28".nid), 
"XGB_Model_0_28" AS 
(SELECT "DT_Output_28"."KEY" AS "KEY", "DT_Output_28"."Score" AS "Score_0" 
FROM "DT_Output_28"), 
"DT_node_lookup_29" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_29" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.137758717 AS "Score" UNION ALL SELECT 2 AS nid, 0.0755570903 AS "Score") AS "Values"), 
"DT_Output_29" AS 
(SELECT "DT_node_lookup_29"."KEY" AS "KEY", "DT_node_lookup_29".node_id_2 AS node_id_2, "DT_node_data_29".nid AS nid, "DT_node_data_29"."Score" AS "Score" 
FROM "DT_node_lookup_29" LEFT OUTER JOIN "DT_node_data_29" ON "DT_node_lookup_29".node_id_2 = "DT_node_data_29".nid), 
"XGB_Model_0_29" AS 
(SELECT "DT_Output_29"."KEY" AS "KEY", "DT_Output_29"."Score" AS "Score_0" 
FROM "DT_Output_29"), 
"XGB_2" AS 
(SELECT "XGB_esu_2"."KEY" AS "KEY", "XGB_esu_2"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_Model_0_20"."KEY" AS "KEY", CAST("XGB_Model_0_20"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_20" UNION ALL SELECT "XGB_Model_0_21"."KEY" AS "KEY", CAST("XGB_Model_0_21"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_21" UNION ALL SELECT "XGB_Model_0_22"."KEY" AS "KEY", CAST("XGB_Model_0_22"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_22" UNION ALL SELECT "XGB_Model_0_23"."KEY" AS "KEY", CAST("XGB_Model_0_23"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_23" UNION ALL SELECT "XGB_Model_0_24"."KEY" AS "KEY", CAST("XGB_Model_0_24"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_24" UNION ALL SELECT "XGB_Model_0_25"."KEY" AS "KEY", CAST("XGB_Model_0_25"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_25" UNION ALL SELECT "XGB_Model_0_26"."KEY" AS "KEY", CAST("XGB_Model_0_26"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_26" UNION ALL SELECT "XGB_Model_0_27"."KEY" AS "KEY", CAST("XGB_Model_0_27"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_27" UNION ALL SELECT "XGB_Model_0_28"."KEY" AS "KEY", CAST("XGB_Model_0_28"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_28" UNION ALL SELECT "XGB_Model_0_29"."KEY" AS "KEY", CAST("XGB_Model_0_29"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_29") AS "XGB_esu_2"), 
"DT_node_lookup_30" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.437053055) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_30" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0534935482 AS "Score" UNION ALL SELECT 2 AS nid, -0.184968114 AS "Score") AS "Values"), 
"DT_Output_30" AS 
(SELECT "DT_node_lookup_30"."KEY" AS "KEY", "DT_node_lookup_30".node_id_2 AS node_id_2, "DT_node_data_30".nid AS nid, "DT_node_data_30"."Score" AS "Score" 
FROM "DT_node_lookup_30" LEFT OUTER JOIN "DT_node_data_30" ON "DT_node_lookup_30".node_id_2 = "DT_node_data_30".nid), 
"XGB_Model_0_30" AS 
(SELECT "DT_Output_30"."KEY" AS "KEY", "DT_Output_30"."Score" AS "Score_0" 
FROM "DT_Output_30"), 
"DT_node_lookup_31" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.547154188) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_31" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.156100675 AS "Score" UNION ALL SELECT 2 AS nid, 0.0521222763 AS "Score") AS "Values"), 
"DT_Output_31" AS 
(SELECT "DT_node_lookup_31"."KEY" AS "KEY", "DT_node_lookup_31".node_id_2 AS node_id_2, "DT_node_data_31".nid AS nid, "DT_node_data_31"."Score" AS "Score" 
FROM "DT_node_lookup_31" LEFT OUTER JOIN "DT_node_data_31" ON "DT_node_lookup_31".node_id_2 = "DT_node_data_31".nid), 
"XGB_Model_0_31" AS 
(SELECT "DT_Output_31"."KEY" AS "KEY", "DT_Output_31"."Score" AS "Score_0" 
FROM "DT_Output_31"), 
"DT_node_lookup_32" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.299286783) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_32" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0594184212 AS "Score" UNION ALL SELECT 2 AS nid, 0.155815005 AS "Score") AS "Values"), 
"DT_Output_32" AS 
(SELECT "DT_node_lookup_32"."KEY" AS "KEY", "DT_node_lookup_32".node_id_2 AS node_id_2, "DT_node_data_32".nid AS nid, "DT_node_data_32"."Score" AS "Score" 
FROM "DT_node_lookup_32" LEFT OUTER JOIN "DT_node_data_32" ON "DT_node_lookup_32".node_id_2 = "DT_node_data_32".nid), 
"XGB_Model_0_32" AS 
(SELECT "DT_Output_32"."KEY" AS "KEY", "DT_Output_32"."Score" AS "Score_0" 
FROM "DT_Output_32"), 
"DT_node_lookup_33" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_33" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.132528663 AS "Score" UNION ALL SELECT 2 AS nid, 0.0671221018 AS "Score") AS "Values"), 
"DT_Output_33" AS 
(SELECT "DT_node_lookup_33"."KEY" AS "KEY", "DT_node_lookup_33".node_id_2 AS node_id_2, "DT_node_data_33".nid AS nid, "DT_node_data_33"."Score" AS "Score" 
FROM "DT_node_lookup_33" LEFT OUTER JOIN "DT_node_data_33" ON "DT_node_lookup_33".node_id_2 = "DT_node_data_33".nid), 
"XGB_Model_0_33" AS 
(SELECT "DT_Output_33"."KEY" AS "KEY", "DT_Output_33"."Score" AS "Score_0" 
FROM "DT_Output_33"), 
"DT_node_lookup_34" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < 1.66039979) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_34" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0498773456 AS "Score" UNION ALL SELECT 2 AS nid, -0.166171134 AS "Score") AS "Values"), 
"DT_Output_34" AS 
(SELECT "DT_node_lookup_34"."KEY" AS "KEY", "DT_node_lookup_34".node_id_2 AS node_id_2, "DT_node_data_34".nid AS nid, "DT_node_data_34"."Score" AS "Score" 
FROM "DT_node_lookup_34" LEFT OUTER JOIN "DT_node_data_34" ON "DT_node_lookup_34".node_id_2 = "DT_node_data_34".nid), 
"XGB_Model_0_34" AS 
(SELECT "DT_Output_34"."KEY" AS "KEY", "DT_Output_34"."Score" AS "Score_0" 
FROM "DT_Output_34"), 
"DT_node_lookup_35" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.437053055) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_35" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0417474657 AS "Score" UNION ALL SELECT 2 AS nid, -0.173644781 AS "Score") AS "Values"), 
"DT_Output_35" AS 
(SELECT "DT_node_lookup_35"."KEY" AS "KEY", "DT_node_lookup_35".node_id_2 AS node_id_2, "DT_node_data_35".nid AS nid, "DT_node_data_35"."Score" AS "Score" 
FROM "DT_node_lookup_35" LEFT OUTER JOIN "DT_node_data_35" ON "DT_node_lookup_35".node_id_2 = "DT_node_data_35".nid), 
"XGB_Model_0_35" AS 
(SELECT "DT_Output_35"."KEY" AS "KEY", "DT_Output_35"."Score" AS "Score_0" 
FROM "DT_Output_35"), 
"DT_node_lookup_36" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_6" < 0.641584754) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_36" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0754463673 AS "Score" UNION ALL SELECT 2 AS nid, 0.102618113 AS "Score") AS "Values"), 
"DT_Output_36" AS 
(SELECT "DT_node_lookup_36"."KEY" AS "KEY", "DT_node_lookup_36".node_id_2 AS node_id_2, "DT_node_data_36".nid AS nid, "DT_node_data_36"."Score" AS "Score" 
FROM "DT_node_lookup_36" LEFT OUTER JOIN "DT_node_data_36" ON "DT_node_lookup_36".node_id_2 = "DT_node_data_36".nid), 
"XGB_Model_0_36" AS 
(SELECT "DT_Output_36"."KEY" AS "KEY", "DT_Output_36"."Score" AS "Score_0" 
FROM "DT_Output_36"), 
"DT_node_lookup_37" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -1.15499079) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_37" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.126855344 AS "Score" UNION ALL SELECT 2 AS nid, 0.0534983613 AS "Score") AS "Values"), 
"DT_Output_37" AS 
(SELECT "DT_node_lookup_37"."KEY" AS "KEY", "DT_node_lookup_37".node_id_2 AS node_id_2, "DT_node_data_37".nid AS nid, "DT_node_data_37"."Score" AS "Score" 
FROM "DT_node_lookup_37" LEFT OUTER JOIN "DT_node_data_37" ON "DT_node_lookup_37".node_id_2 = "DT_node_data_37".nid), 
"XGB_Model_0_37" AS 
(SELECT "DT_Output_37"."KEY" AS "KEY", "DT_Output_37"."Score" AS "Score_0" 
FROM "DT_Output_37"), 
"DT_node_lookup_38" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.335367858) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_38" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.052299425 AS "Score" UNION ALL SELECT 2 AS nid, 0.166599572 AS "Score") AS "Values"), 
"DT_Output_38" AS 
(SELECT "DT_node_lookup_38"."KEY" AS "KEY", "DT_node_lookup_38".node_id_2 AS node_id_2, "DT_node_data_38".nid AS nid, "DT_node_data_38"."Score" AS "Score" 
FROM "DT_node_lookup_38" LEFT OUTER JOIN "DT_node_data_38" ON "DT_node_lookup_38".node_id_2 = "DT_node_data_38".nid), 
"XGB_Model_0_38" AS 
(SELECT "DT_Output_38"."KEY" AS "KEY", "DT_Output_38"."Score" AS "Score_0" 
FROM "DT_Output_38"), 
"DT_node_lookup_39" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.547154188) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_39" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.145151421 AS "Score" UNION ALL SELECT 2 AS nid, 0.0552323423 AS "Score") AS "Values"), 
"DT_Output_39" AS 
(SELECT "DT_node_lookup_39"."KEY" AS "KEY", "DT_node_lookup_39".node_id_2 AS node_id_2, "DT_node_data_39".nid AS nid, "DT_node_data_39"."Score" AS "Score" 
FROM "DT_node_lookup_39" LEFT OUTER JOIN "DT_node_data_39" ON "DT_node_lookup_39".node_id_2 = "DT_node_data_39".nid), 
"XGB_Model_0_39" AS 
(SELECT "DT_Output_39"."KEY" AS "KEY", "DT_Output_39"."Score" AS "Score_0" 
FROM "DT_Output_39"), 
"XGB_3" AS 
(SELECT "XGB_esu_3"."KEY" AS "KEY", "XGB_esu_3"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_Model_0_30"."KEY" AS "KEY", CAST("XGB_Model_0_30"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_30" UNION ALL SELECT "XGB_Model_0_31"."KEY" AS "KEY", CAST("XGB_Model_0_31"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_31" UNION ALL SELECT "XGB_Model_0_32"."KEY" AS "KEY", CAST("XGB_Model_0_32"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_32" UNION ALL SELECT "XGB_Model_0_33"."KEY" AS "KEY", CAST("XGB_Model_0_33"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_33" UNION ALL SELECT "XGB_Model_0_34"."KEY" AS "KEY", CAST("XGB_Model_0_34"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_34" UNION ALL SELECT "XGB_Model_0_35"."KEY" AS "KEY", CAST("XGB_Model_0_35"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_35" UNION ALL SELECT "XGB_Model_0_36"."KEY" AS "KEY", CAST("XGB_Model_0_36"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_36" UNION ALL SELECT "XGB_Model_0_37"."KEY" AS "KEY", CAST("XGB_Model_0_37"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_37" UNION ALL SELECT "XGB_Model_0_38"."KEY" AS "KEY", CAST("XGB_Model_0_38"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_38" UNION ALL SELECT "XGB_Model_0_39"."KEY" AS "KEY", CAST("XGB_Model_0_39"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_39") AS "XGB_esu_3"), 
"DT_node_lookup_40" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_0" < 0.407357097) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_40" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0789353698 AS "Score" UNION ALL SELECT 2 AS nid, 0.083840169 AS "Score") AS "Values"), 
"DT_Output_40" AS 
(SELECT "DT_node_lookup_40"."KEY" AS "KEY", "DT_node_lookup_40".node_id_2 AS node_id_2, "DT_node_data_40".nid AS nid, "DT_node_data_40"."Score" AS "Score" 
FROM "DT_node_lookup_40" LEFT OUTER JOIN "DT_node_data_40" ON "DT_node_lookup_40".node_id_2 = "DT_node_data_40".nid), 
"XGB_Model_0_40" AS 
(SELECT "DT_Output_40"."KEY" AS "KEY", "DT_Output_40"."Score" AS "Score_0" 
FROM "DT_Output_40"), 
"DT_node_lookup_41" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_41" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.123545088 AS "Score" UNION ALL SELECT 2 AS nid, 0.06135213 AS "Score") AS "Values"), 
"DT_Output_41" AS 
(SELECT "DT_node_lookup_41"."KEY" AS "KEY", "DT_node_lookup_41".node_id_2 AS node_id_2, "DT_node_data_41".nid AS nid, "DT_node_data_41"."Score" AS "Score" 
FROM "DT_node_lookup_41" LEFT OUTER JOIN "DT_node_data_41" ON "DT_node_lookup_41".node_id_2 = "DT_node_data_41".nid), 
"XGB_Model_0_41" AS 
(SELECT "DT_Output_41"."KEY" AS "KEY", "DT_Output_41"."Score" AS "Score_0" 
FROM "DT_Output_41"), 
"DT_node_lookup_42" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < 1.66039979) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_42" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0453949571 AS "Score" UNION ALL SELECT 2 AS nid, -0.141670525 AS "Score") AS "Values"), 
"DT_Output_42" AS 
(SELECT "DT_node_lookup_42"."KEY" AS "KEY", "DT_node_lookup_42".node_id_2 AS node_id_2, "DT_node_data_42".nid AS nid, "DT_node_data_42"."Score" AS "Score" 
FROM "DT_node_lookup_42" LEFT OUTER JOIN "DT_node_data_42" ON "DT_node_lookup_42".node_id_2 = "DT_node_data_42".nid), 
"XGB_Model_0_42" AS 
(SELECT "DT_Output_42"."KEY" AS "KEY", "DT_Output_42"."Score" AS "Score_0" 
FROM "DT_Output_42"), 
"DT_node_lookup_43" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_4" < 0.653448939) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_43" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0652215257 AS "Score" UNION ALL SELECT 2 AS nid, 0.106851541 AS "Score") AS "Values"), 
"DT_Output_43" AS 
(SELECT "DT_node_lookup_43"."KEY" AS "KEY", "DT_node_lookup_43".node_id_2 AS node_id_2, "DT_node_data_43".nid AS nid, "DT_node_data_43"."Score" AS "Score" 
FROM "DT_node_lookup_43" LEFT OUTER JOIN "DT_node_data_43" ON "DT_node_lookup_43".node_id_2 = "DT_node_data_43".nid), 
"XGB_Model_0_43" AS 
(SELECT "DT_Output_43"."KEY" AS "KEY", "DT_Output_43"."Score" AS "Score_0" 
FROM "DT_Output_43"), 
"DT_node_lookup_44" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_9" < 0.387014002) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_44" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.049147673 AS "Score" UNION ALL SELECT 2 AS nid, -0.132858127 AS "Score") AS "Values"), 
"DT_Output_44" AS 
(SELECT "DT_node_lookup_44"."KEY" AS "KEY", "DT_node_lookup_44".node_id_2 AS node_id_2, "DT_node_data_44".nid AS nid, "DT_node_data_44"."Score" AS "Score" 
FROM "DT_node_lookup_44" LEFT OUTER JOIN "DT_node_data_44" ON "DT_node_lookup_44".node_id_2 = "DT_node_data_44".nid), 
"XGB_Model_0_44" AS 
(SELECT "DT_Output_44"."KEY" AS "KEY", "DT_Output_44"."Score" AS "Score_0" 
FROM "DT_Output_44"), 
"DT_node_lookup_45" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < -0.984997809) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_45" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.113103762 AS "Score" UNION ALL SELECT 2 AS nid, 0.0527656972 AS "Score") AS "Values"), 
"DT_Output_45" AS 
(SELECT "DT_node_lookup_45"."KEY" AS "KEY", "DT_node_lookup_45".node_id_2 AS node_id_2, "DT_node_data_45".nid AS nid, "DT_node_data_45"."Score" AS "Score" 
FROM "DT_node_lookup_45" LEFT OUTER JOIN "DT_node_data_45" ON "DT_node_lookup_45".node_id_2 = "DT_node_data_45".nid), 
"XGB_Model_0_45" AS 
(SELECT "DT_Output_45"."KEY" AS "KEY", "DT_Output_45"."Score" AS "Score_0" 
FROM "DT_Output_45"), 
"DT_node_lookup_46" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_7" < 0.299286783) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_46" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0516677909 AS "Score" UNION ALL SELECT 2 AS nid, 0.132975042 AS "Score") AS "Values"), 
"DT_Output_46" AS 
(SELECT "DT_node_lookup_46"."KEY" AS "KEY", "DT_node_lookup_46".node_id_2 AS node_id_2, "DT_node_data_46".nid AS nid, "DT_node_data_46"."Score" AS "Score" 
FROM "DT_node_lookup_46" LEFT OUTER JOIN "DT_node_data_46" ON "DT_node_lookup_46".node_id_2 = "DT_node_data_46".nid), 
"XGB_Model_0_46" AS 
(SELECT "DT_Output_46"."KEY" AS "KEY", "DT_Output_46"."Score" AS "Score_0" 
FROM "DT_Output_46"), 
"DT_node_lookup_47" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" < -0.547154188) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_47" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.13110356 AS "Score" UNION ALL SELECT 2 AS nid, 0.0490717888 AS "Score") AS "Values"), 
"DT_Output_47" AS 
(SELECT "DT_node_lookup_47"."KEY" AS "KEY", "DT_node_lookup_47".node_id_2 AS node_id_2, "DT_node_data_47".nid AS nid, "DT_node_data_47"."Score" AS "Score" 
FROM "DT_node_lookup_47" LEFT OUTER JOIN "DT_node_data_47" ON "DT_node_lookup_47".node_id_2 = "DT_node_data_47".nid), 
"XGB_Model_0_47" AS 
(SELECT "DT_Output_47"."KEY" AS "KEY", "DT_Output_47"."Score" AS "Score_0" 
FROM "DT_Output_47"), 
"DT_node_lookup_48" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_6" < 0.641584754) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_48" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, -0.0611261204 AS "Score" UNION ALL SELECT 2 AS nid, 0.0903595686 AS "Score") AS "Values"), 
"DT_Output_48" AS 
(SELECT "DT_node_lookup_48"."KEY" AS "KEY", "DT_node_lookup_48".node_id_2 AS node_id_2, "DT_node_data_48".nid AS nid, "DT_node_data_48"."Score" AS "Score" 
FROM "DT_node_lookup_48" LEFT OUTER JOIN "DT_node_data_48" ON "DT_node_lookup_48".node_id_2 = "DT_node_data_48".nid), 
"XGB_Model_0_48" AS 
(SELECT "DT_Output_48"."KEY" AS "KEY", "DT_Output_48"."Score" AS "Score_0" 
FROM "DT_Output_48"), 
"DT_node_lookup_49" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_5" < 1.66039979) THEN 1 ELSE 2 END AS node_id_2 
FROM "BinaryClass_10" AS "ADS"), 
"DT_node_data_49" AS 
(SELECT "Values".nid AS nid, "Values"."Score" AS "Score" 
FROM (SELECT 1 AS nid, 0.0437743291 AS "Score" UNION ALL SELECT 2 AS nid, -0.120386407 AS "Score") AS "Values"), 
"DT_Output_49" AS 
(SELECT "DT_node_lookup_49"."KEY" AS "KEY", "DT_node_lookup_49".node_id_2 AS node_id_2, "DT_node_data_49".nid AS nid, "DT_node_data_49"."Score" AS "Score" 
FROM "DT_node_lookup_49" LEFT OUTER JOIN "DT_node_data_49" ON "DT_node_lookup_49".node_id_2 = "DT_node_data_49".nid), 
"XGB_Model_0_49" AS 
(SELECT "DT_Output_49"."KEY" AS "KEY", "DT_Output_49"."Score" AS "Score_0" 
FROM "DT_Output_49"), 
"XGB_4" AS 
(SELECT "XGB_esu_4"."KEY" AS "KEY", "XGB_esu_4"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_Model_0_40"."KEY" AS "KEY", CAST("XGB_Model_0_40"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_40" UNION ALL SELECT "XGB_Model_0_41"."KEY" AS "KEY", CAST("XGB_Model_0_41"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_41" UNION ALL SELECT "XGB_Model_0_42"."KEY" AS "KEY", CAST("XGB_Model_0_42"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_42" UNION ALL SELECT "XGB_Model_0_43"."KEY" AS "KEY", CAST("XGB_Model_0_43"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_43" UNION ALL SELECT "XGB_Model_0_44"."KEY" AS "KEY", CAST("XGB_Model_0_44"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_44" UNION ALL SELECT "XGB_Model_0_45"."KEY" AS "KEY", CAST("XGB_Model_0_45"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_45" UNION ALL SELECT "XGB_Model_0_46"."KEY" AS "KEY", CAST("XGB_Model_0_46"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_46" UNION ALL SELECT "XGB_Model_0_47"."KEY" AS "KEY", CAST("XGB_Model_0_47"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_47" UNION ALL SELECT "XGB_Model_0_48"."KEY" AS "KEY", CAST("XGB_Model_0_48"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_48" UNION ALL SELECT "XGB_Model_0_49"."KEY" AS "KEY", CAST("XGB_Model_0_49"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_Model_0_49") AS "XGB_esu_4"), 
"XGB" AS 
(SELECT "XGBbig_esu"."KEY" AS "KEY", "XGBbig_esu"."Score_0" AS "Score_0" 
FROM (SELECT "XGB_0"."KEY" AS "KEY", CAST("XGB_0"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_0" UNION ALL SELECT "XGB_1"."KEY" AS "KEY", CAST("XGB_1"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_1" UNION ALL SELECT "XGB_2"."KEY" AS "KEY", CAST("XGB_2"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_2" UNION ALL SELECT "XGB_3"."KEY" AS "KEY", CAST("XGB_3"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_3" UNION ALL SELECT "XGB_4"."KEY" AS "KEY", CAST("XGB_4"."Score_0" AS DOUBLE) AS "Score_0" 
FROM "XGB_4") AS "XGBbig_esu"), 
"XGB_sum" AS 
(SELECT "T"."KEY" AS "KEY", CAST("T"."Score_0" AS DOUBLE) AS "Score_0" 
FROM (SELECT "XGB"."KEY" AS "KEY", sum("XGB"."Score_0") AS "Score_0" 
FROM "XGB" GROUP BY "XGB"."KEY") AS "T"), 
orig_cte AS 
(SELECT "XGB_sum"."KEY" AS "KEY", "XGB_sum"."Score_0" AS "Score_0", CAST(NULL AS DOUBLE) AS "Score_1", 1.0 - 1.0 / (1.0 + exp(CASE WHEN (100.0 <= CASE WHEN (-100.0 <= -"XGB_sum"."Score_0") THEN -"XGB_sum"."Score_0" ELSE -100.0 END) THEN 100.0 ELSE CASE WHEN (-100.0 <= -"XGB_sum"."Score_0") THEN -"XGB_sum"."Score_0" ELSE -100.0 END END)) AS "Proba_0", 1.0 / (1.0 + exp(CASE WHEN (100.0 <= CASE WHEN (-100.0 <= -"XGB_sum"."Score_0") THEN -"XGB_sum"."Score_0" ELSE -100.0 END) THEN 100.0 ELSE CASE WHEN (-100.0 <= -"XGB_sum"."Score_0") THEN -"XGB_sum"."Score_0" ELSE -100.0 END END)) AS "Proba_1", CAST(NULL AS DOUBLE) AS "LogProba_0", CAST(NULL AS DOUBLE) AS "LogProba_1", CAST(NULL AS BIGINT) AS "Decision", CAST(NULL AS DOUBLE) AS "DecisionProba" 
FROM "XGB_sum"), 
score_class_union AS 
(SELECT scu."KEY_u" AS "KEY_u", scu.class AS class, scu."LogProba" AS "LogProba", scu."Proba" AS "Proba", scu."Score" AS "Score" 
FROM (SELECT orig_cte."KEY" AS "KEY_u", 0 AS class, orig_cte."LogProba_0" AS "LogProba", orig_cte."Proba_0" AS "Proba", orig_cte."Score_0" AS "Score" 
FROM orig_cte UNION ALL SELECT orig_cte."KEY" AS "KEY_u", 1 AS class, orig_cte."LogProba_1" AS "LogProba", orig_cte."Proba_1" AS "Proba", orig_cte."Score_1" AS "Score" 
FROM orig_cte) AS scu), 
score_max AS 
(SELECT orig_cte."KEY" AS "KEY", orig_cte."Score_0" AS "Score_0", orig_cte."Score_1" AS "Score_1", orig_cte."Proba_0" AS "Proba_0", orig_cte."Proba_1" AS "Proba_1", orig_cte."LogProba_0" AS "LogProba_0", orig_cte."LogProba_1" AS "LogProba_1", orig_cte."Decision" AS "Decision", orig_cte."DecisionProba" AS "DecisionProba", max_select."KEY_m" AS "KEY_m", max_select."max_Proba" AS "max_Proba" 
FROM orig_cte LEFT OUTER JOIN (SELECT score_class_union."KEY_u" AS "KEY_m", max(score_class_union."Proba") AS "max_Proba" 
FROM score_class_union GROUP BY score_class_union."KEY_u") AS max_select ON orig_cte."KEY" = max_select."KEY_m"), 
union_with_max AS 
(SELECT score_class_union."KEY_u" AS "KEY_u", score_class_union.class AS class, score_class_union."LogProba" AS "LogProba", score_class_union."Proba" AS "Proba", score_class_union."Score" AS "Score", score_max."KEY" AS "KEY", score_max."Score_0" AS "Score_0", score_max."Score_1" AS "Score_1", score_max."Proba_0" AS "Proba_0", score_max."Proba_1" AS "Proba_1", score_max."LogProba_0" AS "LogProba_0", score_max."LogProba_1" AS "LogProba_1", score_max."Decision" AS "Decision", score_max."DecisionProba" AS "DecisionProba", score_max."KEY_m" AS "KEY_m", score_max."max_Proba" AS "max_Proba" 
FROM score_class_union LEFT OUTER JOIN score_max ON score_class_union."KEY_u" = score_max."KEY"), 
arg_max_cte AS 
(SELECT score_max."KEY" AS "KEY", score_max."Score_0" AS "Score_0", score_max."Score_1" AS "Score_1", score_max."Proba_0" AS "Proba_0", score_max."Proba_1" AS "Proba_1", score_max."LogProba_0" AS "LogProba_0", score_max."LogProba_1" AS "LogProba_1", score_max."Decision" AS "Decision", score_max."DecisionProba" AS "DecisionProba", score_max."KEY_m" AS "KEY_m", score_max."max_Proba" AS "max_Proba", "arg_max_t_Proba"."KEY_Proba" AS "KEY_Proba", "arg_max_t_Proba"."arg_max_Proba" AS "arg_max_Proba" 
FROM score_max LEFT OUTER JOIN (SELECT union_with_max."KEY" AS "KEY_Proba", min(union_with_max.class) AS "arg_max_Proba" 
FROM union_with_max 
WHERE union_with_max."max_Proba" <= union_with_max."Proba" GROUP BY union_with_max."KEY") AS "arg_max_t_Proba" ON score_max."KEY" = "arg_max_t_Proba"."KEY_Proba")
 SELECT arg_max_cte."KEY" AS "KEY", CAST(NULL AS DOUBLE) AS "Score_0", CAST(NULL AS DOUBLE) AS "Score_1", arg_max_cte."Proba_0" AS "Proba_0", arg_max_cte."Proba_1" AS "Proba_1", log(CASE WHEN (arg_max_cte."Proba_0" IS NULL OR arg_max_cte."Proba_0" > 1e-100) THEN arg_max_cte."Proba_0" ELSE 1e-100 END) AS "LogProba_0", log(CASE WHEN (arg_max_cte."Proba_1" IS NULL OR arg_max_cte."Proba_1" > 1e-100) THEN arg_max_cte."Proba_1" ELSE 1e-100 END) AS "LogProba_1", arg_max_cte."arg_max_Proba" AS "Decision", arg_max_cte."max_Proba" AS "DecisionProba" 
FROM arg_max_cte