-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretRegressor_nnet
-- Dataset : freidman2
-- Database : mysql


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH `IL` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CAST(`ADS`.`Feature_0` AS DOUBLE) AS `Feature_0`, CAST(`ADS`.`Feature_1` AS DOUBLE) AS `Feature_1`, CAST(`ADS`.`Feature_2` AS DOUBLE) AS `Feature_2`, CAST(`ADS`.`Feature_3` AS DOUBLE) AS `Feature_3` 
FROM freidman2 AS `ADS`), 
`HL_BA_1` AS 
(SELECT `IL`.`KEY` AS `KEY`, -0.004996092 * `IL`.`Feature_0` + 0.004419708 * `IL`.`Feature_1` + 9.781767 * `IL`.`Feature_2` + 0.0853716 * `IL`.`Feature_3` + -11.73083 AS `NEUR_1_1`, -0.02826975 * `IL`.`Feature_0` + -2.611865 * `IL`.`Feature_1` + -0.006611729 * `IL`.`Feature_2` + -0.2039825 * `IL`.`Feature_3` + -0.0230614 AS `NEUR_1_2`, -0.2065835 * `IL`.`Feature_0` + -0.4406876 * `IL`.`Feature_1` + -0.001226009 * `IL`.`Feature_2` + -0.002880574 * `IL`.`Feature_3` + -0.003676619 AS `NEUR_1_3`, -0.1232436 * `IL`.`Feature_0` + -0.3576857 * `IL`.`Feature_1` + -0.0003189939 * `IL`.`Feature_2` + -0.006789236 * `IL`.`Feature_3` + 0.0003522122 AS `NEUR_1_4`, -1.796196 * `IL`.`Feature_0` + 0.2872978 * `IL`.`Feature_1` + -34.94005 * `IL`.`Feature_2` + -22.42768 * `IL`.`Feature_3` + 14.90131 AS `NEUR_1_5` 
FROM `IL`), 
`HL_1_logistic` AS 
(SELECT `HL_BA_1`.`KEY` AS `KEY`, 1.0 / (1.0 + exp(least(100.0, greatest(-100.0, -`HL_BA_1`.`NEUR_1_1`)))) AS `NEUR_1_1`, 1.0 / (1.0 + exp(least(100.0, greatest(-100.0, -`HL_BA_1`.`NEUR_1_2`)))) AS `NEUR_1_2`, 1.0 / (1.0 + exp(least(100.0, greatest(-100.0, -`HL_BA_1`.`NEUR_1_3`)))) AS `NEUR_1_3`, 1.0 / (1.0 + exp(least(100.0, greatest(-100.0, -`HL_BA_1`.`NEUR_1_4`)))) AS `NEUR_1_4`, 1.0 / (1.0 + exp(least(100.0, greatest(-100.0, -`HL_BA_1`.`NEUR_1_5`)))) AS `NEUR_1_5` 
FROM `HL_BA_1`), 
`HL_1_logistic_1` AS 
(SELECT `HL_1_logistic`.`KEY` AS `KEY`, `HL_1_logistic`.`NEUR_1_1` AS `NEUR_1_1`, `HL_1_logistic`.`NEUR_1_2` AS `NEUR_1_2`, `HL_1_logistic`.`NEUR_1_3` AS `NEUR_1_3`, `HL_1_logistic`.`NEUR_1_4` AS `NEUR_1_4`, `HL_1_logistic`.`NEUR_1_5` AS `NEUR_1_5` 
FROM `HL_1_logistic`), 
`OL_BA` AS 
(SELECT `HL_1_logistic_1`.`KEY` AS `KEY`, 731.6842 * `HL_1_logistic_1`.`NEUR_1_1` + 3.455241 * `HL_1_logistic_1`.`NEUR_1_2` + -0.03328912 * `HL_1_logistic_1`.`NEUR_1_3` + -0.05732999 * `HL_1_logistic_1`.`NEUR_1_4` + 141.3363 * `HL_1_logistic_1`.`NEUR_1_5` + 172.6983 AS `NEUR_2_1` 
FROM `HL_1_logistic_1`), 
`OL_identity` AS 
(SELECT `OL_BA`.`KEY` AS `KEY`, `OL_BA`.`NEUR_2_1` AS `NEUR_2_1` 
FROM `OL_BA`), 
`OL_identity_1` AS 
(SELECT `OL_identity`.`KEY` AS `KEY`, `OL_identity`.`NEUR_2_1` AS `NEUR_2_1` 
FROM `OL_identity`)
 SELECT `OL_identity_1`.`KEY` AS `KEY`, `OL_identity_1`.`NEUR_2_1` AS `Estimator` 
FROM `OL_identity_1`