-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretRegressor_earth
-- Dataset : diabetes
-- Database : teradata


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH earth_input AS 
(SELECT "ADS"."KEY" AS "KEY", CAST("ADS"."Feature_0" AS DOUBLE PRECISION) AS "Feature_0", CAST("ADS"."Feature_1" AS DOUBLE PRECISION) AS "Feature_1", CAST("ADS"."Feature_2" AS DOUBLE PRECISION) AS "Feature_2", CAST("ADS"."Feature_3" AS DOUBLE PRECISION) AS "Feature_3", CAST("ADS"."Feature_4" AS DOUBLE PRECISION) AS "Feature_4", CAST("ADS"."Feature_5" AS DOUBLE PRECISION) AS "Feature_5", CAST("ADS"."Feature_6" AS DOUBLE PRECISION) AS "Feature_6", CAST("ADS"."Feature_7" AS DOUBLE PRECISION) AS "Feature_7", CAST("ADS"."Feature_8" AS DOUBLE PRECISION) AS "Feature_8", CAST("ADS"."Feature_9" AS DOUBLE PRECISION) AS "Feature_9" 
FROM diabetes AS "ADS"), 
earth_model_cte AS 
(SELECT earth_input."KEY" AS "KEY", CAST(540.9158596123267 AS DOUBLE PRECISION) * greatest(earth_input."Feature_2" - CAST(-0.051474061238806 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(857.8811426179631 AS DOUBLE PRECISION) * greatest(earth_input."Feature_8" - CAST(-0.061176595094334 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(585.6663066748639 AS DOUBLE PRECISION) * greatest(earth_input."Feature_3" - CAST(0.014986613607483 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(-185.62767022292832 AS DOUBLE PRECISION) * earth_input."Feature_1" + CAST(288.9614021070438 AS DOUBLE PRECISION) * greatest(earth_input."Feature_9" - CAST(0.011348623244038 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(-770.2410768775819 AS DOUBLE PRECISION) * greatest(earth_input."Feature_4" - CAST(-0.075870414163072 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(607.3354601229668 AS DOUBLE PRECISION) * greatest(earth_input."Feature_5" - CAST(-0.034507614375909 AS DOUBLE PRECISION), CAST(0 AS DOUBLE PRECISION)) + CAST(92.34557859695556 AS DOUBLE PRECISION) AS "Estimator" 
FROM earth_input)
 SELECT earth_model_cte."KEY" AS "KEY", earth_model_cte."Estimator" AS "Estimator" 
FROM earth_model_cte