-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretClassifier_rf
-- Dataset : BinaryClass_100
-- Database : mysql


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH `RF_0` AS 
(WITH `DT_node_lookup` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.0739414183637216) THEN CASE WHEN (`ADS`.`Feature_88` <= 0.6732887153852776) THEN 3 ELSE CASE WHEN (`ADS`.`Feature_71` <= -0.7058234049590013) THEN 7 ELSE 8 END END ELSE CASE WHEN (`ADS`.`Feature_54` <= 1.4712511209554415) THEN 5 ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output` AS 
(SELECT `DT_node_lookup`.`KEY` AS `KEY`, `DT_node_lookup`.node_id_2 AS node_id_2, `DT_node_data`.nid AS nid, `DT_node_data`.`P_0` AS `P_0`, `DT_node_data`.`P_1` AS `P_1`, `DT_node_data`.`D` AS `D`, `DT_node_data`.`DP` AS `DP` 
FROM `DT_node_lookup` LEFT OUTER JOIN `DT_node_data` ON `DT_node_lookup`.node_id_2 = `DT_node_data`.nid), 
`RF_Model_0` AS 
(SELECT `DT_Output`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output`.`P_0` IS NULL OR `DT_Output`.`P_0` > 0.0) THEN ln(`DT_Output`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output`.`P_1` IS NULL OR `DT_Output`.`P_1` > 0.0) THEN ln(`DT_Output`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output`), 
`DT_node_lookup_1` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_4` <= 0.9146118977733426) THEN CASE WHEN (`ADS`.`Feature_32` <= -0.06323711586883657) THEN CASE WHEN (`ADS`.`Feature_57` <= 0.5804003698683945) THEN CASE WHEN (`ADS`.`Feature_13` <= 0.2920932037116412) THEN 9 ELSE CASE WHEN (`ADS`.`Feature_34` <= 1.4650529347637722) THEN 11 ELSE 12 END END ELSE 6 END ELSE CASE WHEN (`ADS`.`Feature_33` <= -1.5543387949212537) THEN 7 ELSE 8 END END ELSE 2 END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_1` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 2 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_1` AS 
(SELECT `DT_node_lookup_1`.`KEY` AS `KEY`, `DT_node_lookup_1`.node_id_2 AS node_id_2, `DT_node_data_1`.nid AS nid, `DT_node_data_1`.`P_0` AS `P_0`, `DT_node_data_1`.`P_1` AS `P_1`, `DT_node_data_1`.`D` AS `D`, `DT_node_data_1`.`DP` AS `DP` 
FROM `DT_node_lookup_1` LEFT OUTER JOIN `DT_node_data_1` ON `DT_node_lookup_1`.node_id_2 = `DT_node_data_1`.nid), 
`RF_Model_1` AS 
(SELECT `DT_Output_1`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_1`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_1`.`P_0` IS NULL OR `DT_Output_1`.`P_0` > 0.0) THEN ln(`DT_Output_1`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_1`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_1`.`P_1` IS NULL OR `DT_Output_1`.`P_1` > 0.0) THEN ln(`DT_Output_1`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_1`), 
`DT_node_lookup_2` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.27291035218112153) THEN CASE WHEN (`ADS`.`Feature_30` <= 1.595907972776737) THEN CASE WHEN (`ADS`.`Feature_89` <= -2.543229636524592) THEN 7 ELSE CASE WHEN (`ADS`.`Feature_88` <= 1.847425761318168) THEN 13 ELSE 14 END END ELSE CASE WHEN (`ADS`.`Feature_59` <= 0.005661787271904861) THEN 9 ELSE 10 END END ELSE CASE WHEN (`ADS`.`Feature_49` <= 0.8579483258235266) THEN 5 ELSE CASE WHEN (`ADS`.`Feature_43` <= 1.165162465522163) THEN 11 ELSE 12 END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_2` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 13 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 14 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_2` AS 
(SELECT `DT_node_lookup_2`.`KEY` AS `KEY`, `DT_node_lookup_2`.node_id_2 AS node_id_2, `DT_node_data_2`.nid AS nid, `DT_node_data_2`.`P_0` AS `P_0`, `DT_node_data_2`.`P_1` AS `P_1`, `DT_node_data_2`.`D` AS `D`, `DT_node_data_2`.`DP` AS `DP` 
FROM `DT_node_lookup_2` LEFT OUTER JOIN `DT_node_data_2` ON `DT_node_lookup_2`.node_id_2 = `DT_node_data_2`.nid), 
`RF_Model_2` AS 
(SELECT `DT_Output_2`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_2`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_2`.`P_0` IS NULL OR `DT_Output_2`.`P_0` > 0.0) THEN ln(`DT_Output_2`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_2`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_2`.`P_1` IS NULL OR `DT_Output_2`.`P_1` > 0.0) THEN ln(`DT_Output_2`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_2`), 
`DT_node_lookup_3` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= 0.04451274756626045) THEN CASE WHEN (`ADS`.`Feature_18` <= -1.4826767915354522) THEN CASE WHEN (`ADS`.`Feature_45` <= -0.5007415988552348) THEN 5 ELSE 6 END ELSE 4 END ELSE 2 END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_3` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 2 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 4 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_3` AS 
(SELECT `DT_node_lookup_3`.`KEY` AS `KEY`, `DT_node_lookup_3`.node_id_2 AS node_id_2, `DT_node_data_3`.nid AS nid, `DT_node_data_3`.`P_0` AS `P_0`, `DT_node_data_3`.`P_1` AS `P_1`, `DT_node_data_3`.`D` AS `D`, `DT_node_data_3`.`DP` AS `DP` 
FROM `DT_node_lookup_3` LEFT OUTER JOIN `DT_node_data_3` ON `DT_node_lookup_3`.node_id_2 = `DT_node_data_3`.nid), 
`RF_Model_3` AS 
(SELECT `DT_Output_3`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_3`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_3`.`P_0` IS NULL OR `DT_Output_3`.`P_0` > 0.0) THEN ln(`DT_Output_3`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_3`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_3`.`P_1` IS NULL OR `DT_Output_3`.`P_1` > 0.0) THEN ln(`DT_Output_3`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_3`), 
`DT_node_lookup_4` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.29480912843714746) THEN CASE WHEN (`ADS`.`Feature_60` <= -0.6577232275654441) THEN CASE WHEN (`ADS`.`Feature_10` <= -0.9991001503669914) THEN 7 ELSE 8 END ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_74` <= -1.6449173373255075) THEN 5 ELSE CASE WHEN (`ADS`.`Feature_59` <= -1.754531236843976) THEN 9 ELSE CASE WHEN (`ADS`.`Feature_72` <= 1.9118612762894516) THEN 11 ELSE 12 END END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_4` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 4 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_4` AS 
(SELECT `DT_node_lookup_4`.`KEY` AS `KEY`, `DT_node_lookup_4`.node_id_2 AS node_id_2, `DT_node_data_4`.nid AS nid, `DT_node_data_4`.`P_0` AS `P_0`, `DT_node_data_4`.`P_1` AS `P_1`, `DT_node_data_4`.`D` AS `D`, `DT_node_data_4`.`DP` AS `DP` 
FROM `DT_node_lookup_4` LEFT OUTER JOIN `DT_node_data_4` ON `DT_node_lookup_4`.node_id_2 = `DT_node_data_4`.nid), 
`RF_Model_4` AS 
(SELECT `DT_Output_4`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_4`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_4`.`P_0` IS NULL OR `DT_Output_4`.`P_0` > 0.0) THEN ln(`DT_Output_4`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_4`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_4`.`P_1` IS NULL OR `DT_Output_4`.`P_1` > 0.0) THEN ln(`DT_Output_4`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_4`), 
`DT_node_lookup_5` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_4` <= -0.4814718983166721) THEN CASE WHEN (`ADS`.`Feature_61` <= -0.9030823767603314) THEN 3 ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_60` <= -0.6577232275654441) THEN CASE WHEN (`ADS`.`Feature_76` <= 0.05509109872807852) THEN 7 ELSE 8 END ELSE CASE WHEN (`ADS`.`Feature_67` <= 1.1675362895972368) THEN CASE WHEN (`ADS`.`Feature_48` <= -1.958516195314138) THEN 11 ELSE 12 END ELSE CASE WHEN (`ADS`.`Feature_52` <= 0.27285491803287587) THEN 13 ELSE 14 END END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_5` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 4 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 13 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 14 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_5` AS 
(SELECT `DT_node_lookup_5`.`KEY` AS `KEY`, `DT_node_lookup_5`.node_id_2 AS node_id_2, `DT_node_data_5`.nid AS nid, `DT_node_data_5`.`P_0` AS `P_0`, `DT_node_data_5`.`P_1` AS `P_1`, `DT_node_data_5`.`D` AS `D`, `DT_node_data_5`.`DP` AS `DP` 
FROM `DT_node_lookup_5` LEFT OUTER JOIN `DT_node_data_5` ON `DT_node_lookup_5`.node_id_2 = `DT_node_data_5`.nid), 
`RF_Model_5` AS 
(SELECT `DT_Output_5`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_5`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_5`.`P_0` IS NULL OR `DT_Output_5`.`P_0` > 0.0) THEN ln(`DT_Output_5`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_5`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_5`.`P_1` IS NULL OR `DT_Output_5`.`P_1` > 0.0) THEN ln(`DT_Output_5`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_5`), 
`DT_node_lookup_6` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= 0.03130749699721192) THEN CASE WHEN (`ADS`.`Feature_88` <= 0.7153308630841408) THEN CASE WHEN (`ADS`.`Feature_46` <= -1.644739083819518) THEN 7 ELSE 8 END ELSE CASE WHEN (`ADS`.`Feature_83` <= 1.302941805918531) THEN 9 ELSE 10 END END ELSE CASE WHEN (`ADS`.`Feature_65` <= -0.7439982065571124) THEN CASE WHEN (`ADS`.`Feature_4` <= -0.9179261441462784) THEN 11 ELSE 12 END ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_6` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 6 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_6` AS 
(SELECT `DT_node_lookup_6`.`KEY` AS `KEY`, `DT_node_lookup_6`.node_id_2 AS node_id_2, `DT_node_data_6`.nid AS nid, `DT_node_data_6`.`P_0` AS `P_0`, `DT_node_data_6`.`P_1` AS `P_1`, `DT_node_data_6`.`D` AS `D`, `DT_node_data_6`.`DP` AS `DP` 
FROM `DT_node_lookup_6` LEFT OUTER JOIN `DT_node_data_6` ON `DT_node_lookup_6`.node_id_2 = `DT_node_data_6`.nid), 
`RF_Model_6` AS 
(SELECT `DT_Output_6`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_6`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_6`.`P_0` IS NULL OR `DT_Output_6`.`P_0` > 0.0) THEN ln(`DT_Output_6`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_6`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_6`.`P_1` IS NULL OR `DT_Output_6`.`P_1` > 0.0) THEN ln(`DT_Output_6`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_6`), 
`DT_node_lookup_7` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.1960596245956389) THEN CASE WHEN (`ADS`.`Feature_17` <= 1.0863247607574569) THEN 3 ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_18` <= 1.509636037348534) THEN 5 ELSE CASE WHEN (`ADS`.`Feature_72` <= -0.0363141827219442) THEN 7 ELSE 8 END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_7` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 4 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_7` AS 
(SELECT `DT_node_lookup_7`.`KEY` AS `KEY`, `DT_node_lookup_7`.node_id_2 AS node_id_2, `DT_node_data_7`.nid AS nid, `DT_node_data_7`.`P_0` AS `P_0`, `DT_node_data_7`.`P_1` AS `P_1`, `DT_node_data_7`.`D` AS `D`, `DT_node_data_7`.`DP` AS `DP` 
FROM `DT_node_lookup_7` LEFT OUTER JOIN `DT_node_data_7` ON `DT_node_lookup_7`.node_id_2 = `DT_node_data_7`.nid), 
`RF_Model_7` AS 
(SELECT `DT_Output_7`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_7`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_7`.`P_0` IS NULL OR `DT_Output_7`.`P_0` > 0.0) THEN ln(`DT_Output_7`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_7`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_7`.`P_1` IS NULL OR `DT_Output_7`.`P_1` > 0.0) THEN ln(`DT_Output_7`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_7`), 
`DT_node_lookup_8` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.0739414183637216) THEN CASE WHEN (`ADS`.`Feature_82` <= -1.478374859591188) THEN 3 ELSE CASE WHEN (`ADS`.`Feature_5` <= 2.0217014553159647) THEN CASE WHEN (`ADS`.`Feature_89` <= -1.1077254022728402) THEN CASE WHEN (`ADS`.`Feature_60` <= 0.09308929013909567) THEN 11 ELSE 12 END ELSE CASE WHEN (`ADS`.`Feature_46` <= -1.6023069080129182) THEN 13 ELSE 14 END END ELSE 8 END END ELSE CASE WHEN (`ADS`.`Feature_76` <= 1.1987483394867988) THEN 5 ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_8` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 13 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 14 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_8` AS 
(SELECT `DT_node_lookup_8`.`KEY` AS `KEY`, `DT_node_lookup_8`.node_id_2 AS node_id_2, `DT_node_data_8`.nid AS nid, `DT_node_data_8`.`P_0` AS `P_0`, `DT_node_data_8`.`P_1` AS `P_1`, `DT_node_data_8`.`D` AS `D`, `DT_node_data_8`.`DP` AS `DP` 
FROM `DT_node_lookup_8` LEFT OUTER JOIN `DT_node_data_8` ON `DT_node_lookup_8`.node_id_2 = `DT_node_data_8`.nid), 
`RF_Model_8` AS 
(SELECT `DT_Output_8`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_8`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_8`.`P_0` IS NULL OR `DT_Output_8`.`P_0` > 0.0) THEN ln(`DT_Output_8`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_8`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_8`.`P_1` IS NULL OR `DT_Output_8`.`P_1` > 0.0) THEN ln(`DT_Output_8`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_8`), 
`DT_node_lookup_9` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.29480912843714746) THEN CASE WHEN (`ADS`.`Feature_17` <= 1.0863247607574569) THEN 3 ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_84` <= 1.6011269142878592) THEN CASE WHEN (`ADS`.`Feature_18` <= 2.031713036562732) THEN 7 ELSE 8 END ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_9` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 4 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_9` AS 
(SELECT `DT_node_lookup_9`.`KEY` AS `KEY`, `DT_node_lookup_9`.node_id_2 AS node_id_2, `DT_node_data_9`.nid AS nid, `DT_node_data_9`.`P_0` AS `P_0`, `DT_node_data_9`.`P_1` AS `P_1`, `DT_node_data_9`.`D` AS `D`, `DT_node_data_9`.`DP` AS `DP` 
FROM `DT_node_lookup_9` LEFT OUTER JOIN `DT_node_data_9` ON `DT_node_lookup_9`.node_id_2 = `DT_node_data_9`.nid), 
`RF_Model_9` AS 
(SELECT `DT_Output_9`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_9`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_9`.`P_0` IS NULL OR `DT_Output_9`.`P_0` > 0.0) THEN ln(`DT_Output_9`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_9`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_9`.`P_1` IS NULL OR `DT_Output_9`.`P_1` > 0.0) THEN ln(`DT_Output_9`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_9`)
 SELECT `RF_esu_0`.`KEY`, `RF_esu_0`.`Score_0`, `RF_esu_0`.`Proba_0`, `RF_esu_0`.`LogProba_0`, `RF_esu_0`.`Score_1`, `RF_esu_0`.`Proba_1`, `RF_esu_0`.`LogProba_1` 
FROM (SELECT `RF_Model_0`.`KEY` AS `KEY`, CAST(`RF_Model_0`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_0`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_0`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_0`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_0`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_0`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_0` UNION ALL SELECT `RF_Model_1`.`KEY` AS `KEY`, CAST(`RF_Model_1`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_1`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_1`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_1`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_1`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_1`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_1` UNION ALL SELECT `RF_Model_2`.`KEY` AS `KEY`, CAST(`RF_Model_2`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_2`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_2`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_2`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_2`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_2`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_2` UNION ALL SELECT `RF_Model_3`.`KEY` AS `KEY`, CAST(`RF_Model_3`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_3`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_3`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_3`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_3`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_3`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_3` UNION ALL SELECT `RF_Model_4`.`KEY` AS `KEY`, CAST(`RF_Model_4`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_4`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_4`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_4`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_4`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_4`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_4` UNION ALL SELECT `RF_Model_5`.`KEY` AS `KEY`, CAST(`RF_Model_5`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_5`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_5`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_5`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_5`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_5`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_5` UNION ALL SELECT `RF_Model_6`.`KEY` AS `KEY`, CAST(`RF_Model_6`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_6`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_6`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_6`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_6`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_6`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_6` UNION ALL SELECT `RF_Model_7`.`KEY` AS `KEY`, CAST(`RF_Model_7`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_7`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_7`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_7`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_7`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_7`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_7` UNION ALL SELECT `RF_Model_8`.`KEY` AS `KEY`, CAST(`RF_Model_8`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_8`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_8`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_8`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_8`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_8`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_8` UNION ALL SELECT `RF_Model_9`.`KEY` AS `KEY`, CAST(`RF_Model_9`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_9`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_9`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_9`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_9`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_9`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_9`) AS `RF_esu_0`), 
`RF_1` AS 
(WITH `DT_node_lookup_10` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_4` <= -0.0820240403406013) THEN 1 ELSE CASE WHEN (`ADS`.`Feature_35` <= -0.983311491473182) THEN 3 ELSE CASE WHEN (`ADS`.`Feature_88` <= 1.0602924013319153) THEN CASE WHEN (`ADS`.`Feature_41` <= 2.1810966614485707) THEN CASE WHEN (`ADS`.`Feature_57` <= 0.03130749699721192) THEN 11 ELSE 12 END ELSE 8 END ELSE CASE WHEN (`ADS`.`Feature_41` <= -0.3308111152859805) THEN 9 ELSE 10 END END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_10` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 1 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 3 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_10` AS 
(SELECT `DT_node_lookup_10`.`KEY` AS `KEY`, `DT_node_lookup_10`.node_id_2 AS node_id_2, `DT_node_data_10`.nid AS nid, `DT_node_data_10`.`P_0` AS `P_0`, `DT_node_data_10`.`P_1` AS `P_1`, `DT_node_data_10`.`D` AS `D`, `DT_node_data_10`.`DP` AS `DP` 
FROM `DT_node_lookup_10` LEFT OUTER JOIN `DT_node_data_10` ON `DT_node_lookup_10`.node_id_2 = `DT_node_data_10`.nid), 
`RF_Model_10` AS 
(SELECT `DT_Output_10`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_10`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_10`.`P_0` IS NULL OR `DT_Output_10`.`P_0` > 0.0) THEN ln(`DT_Output_10`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_10`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_10`.`P_1` IS NULL OR `DT_Output_10`.`P_1` > 0.0) THEN ln(`DT_Output_10`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_10`), 
`DT_node_lookup_11` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_77` <= 0.03445534730526346) THEN CASE WHEN (`ADS`.`Feature_18` <= 1.1307785551224945) THEN 3 ELSE CASE WHEN (`ADS`.`Feature_76` <= -0.7687101860491407) THEN 7 ELSE 8 END END ELSE CASE WHEN (`ADS`.`Feature_35` <= 0.7510338119100196) THEN 5 ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_11` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_11` AS 
(SELECT `DT_node_lookup_11`.`KEY` AS `KEY`, `DT_node_lookup_11`.node_id_2 AS node_id_2, `DT_node_data_11`.nid AS nid, `DT_node_data_11`.`P_0` AS `P_0`, `DT_node_data_11`.`P_1` AS `P_1`, `DT_node_data_11`.`D` AS `D`, `DT_node_data_11`.`DP` AS `DP` 
FROM `DT_node_lookup_11` LEFT OUTER JOIN `DT_node_data_11` ON `DT_node_lookup_11`.node_id_2 = `DT_node_data_11`.nid), 
`RF_Model_11` AS 
(SELECT `DT_Output_11`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_11`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_11`.`P_0` IS NULL OR `DT_Output_11`.`P_0` > 0.0) THEN ln(`DT_Output_11`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_11`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_11`.`P_1` IS NULL OR `DT_Output_11`.`P_1` > 0.0) THEN ln(`DT_Output_11`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_11`), 
`DT_node_lookup_12` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_20` <= 0.8080772131984651) THEN CASE WHEN (`ADS`.`Feature_4` <= -0.894787708071455) THEN 3 ELSE CASE WHEN (`ADS`.`Feature_37` <= 1.6649534114689295) THEN CASE WHEN (`ADS`.`Feature_82` <= 1.83971289435304) THEN CASE WHEN (`ADS`.`Feature_66` <= 1.7507586660302141) THEN CASE WHEN (`ADS`.`Feature_82` <= -1.4707817632476112) THEN 13 ELSE 14 END ELSE 12 END ELSE 10 END ELSE 8 END END ELSE CASE WHEN (`ADS`.`Feature_24` <= 0.6039787961870529) THEN 5 ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_12` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 13 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 14 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_12` AS 
(SELECT `DT_node_lookup_12`.`KEY` AS `KEY`, `DT_node_lookup_12`.node_id_2 AS node_id_2, `DT_node_data_12`.nid AS nid, `DT_node_data_12`.`P_0` AS `P_0`, `DT_node_data_12`.`P_1` AS `P_1`, `DT_node_data_12`.`D` AS `D`, `DT_node_data_12`.`DP` AS `DP` 
FROM `DT_node_lookup_12` LEFT OUTER JOIN `DT_node_data_12` ON `DT_node_lookup_12`.node_id_2 = `DT_node_data_12`.nid), 
`RF_Model_12` AS 
(SELECT `DT_Output_12`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_12`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_12`.`P_0` IS NULL OR `DT_Output_12`.`P_0` > 0.0) THEN ln(`DT_Output_12`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_12`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_12`.`P_1` IS NULL OR `DT_Output_12`.`P_1` > 0.0) THEN ln(`DT_Output_12`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_12`), 
`DT_node_lookup_13` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.27291035218112153) THEN CASE WHEN (`ADS`.`Feature_60` <= -0.489855367042203) THEN CASE WHEN (`ADS`.`Feature_56` <= -0.09329727136152702) THEN 7 ELSE 8 END ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_6` <= -0.9415949989296384) THEN CASE WHEN (`ADS`.`Feature_21` <= -0.7310564937552343) THEN 9 ELSE 10 END ELSE 6 END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_13` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 4 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 9 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_13` AS 
(SELECT `DT_node_lookup_13`.`KEY` AS `KEY`, `DT_node_lookup_13`.node_id_2 AS node_id_2, `DT_node_data_13`.nid AS nid, `DT_node_data_13`.`P_0` AS `P_0`, `DT_node_data_13`.`P_1` AS `P_1`, `DT_node_data_13`.`D` AS `D`, `DT_node_data_13`.`DP` AS `DP` 
FROM `DT_node_lookup_13` LEFT OUTER JOIN `DT_node_data_13` ON `DT_node_lookup_13`.node_id_2 = `DT_node_data_13`.nid), 
`RF_Model_13` AS 
(SELECT `DT_Output_13`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_13`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_13`.`P_0` IS NULL OR `DT_Output_13`.`P_0` > 0.0) THEN ln(`DT_Output_13`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_13`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_13`.`P_1` IS NULL OR `DT_Output_13`.`P_1` > 0.0) THEN ln(`DT_Output_13`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_13`), 
`DT_node_lookup_14` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_4` <= -0.765736249146654) THEN CASE WHEN (`ADS`.`Feature_37` <= -1.1140145490191613) THEN 3 ELSE 4 END ELSE CASE WHEN (`ADS`.`Feature_54` <= -0.18765020265968127) THEN CASE WHEN (`ADS`.`Feature_90` <= 0.685876339227268) THEN 7 ELSE 8 END ELSE CASE WHEN (`ADS`.`Feature_71` <= -0.8295645921939142) THEN CASE WHEN (`ADS`.`Feature_29` <= 0.1706185049094251) THEN 11 ELSE 12 END ELSE 10 END END END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_14` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 3 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 4 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 10 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 11 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 12 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_14` AS 
(SELECT `DT_node_lookup_14`.`KEY` AS `KEY`, `DT_node_lookup_14`.node_id_2 AS node_id_2, `DT_node_data_14`.nid AS nid, `DT_node_data_14`.`P_0` AS `P_0`, `DT_node_data_14`.`P_1` AS `P_1`, `DT_node_data_14`.`D` AS `D`, `DT_node_data_14`.`DP` AS `DP` 
FROM `DT_node_lookup_14` LEFT OUTER JOIN `DT_node_data_14` ON `DT_node_lookup_14`.node_id_2 = `DT_node_data_14`.nid), 
`RF_Model_14` AS 
(SELECT `DT_Output_14`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_14`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_14`.`P_0` IS NULL OR `DT_Output_14`.`P_0` > 0.0) THEN ln(`DT_Output_14`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_14`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_14`.`P_1` IS NULL OR `DT_Output_14`.`P_1` > 0.0) THEN ln(`DT_Output_14`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_14`), 
`DT_node_lookup_15` AS 
(SELECT `ADS`.`KEY` AS `KEY`, CASE WHEN (`ADS`.`Feature_57` <= -0.20116813993702318) THEN CASE WHEN (`ADS`.`Feature_35` <= 0.7510338119100196) THEN CASE WHEN (`ADS`.`Feature_17` <= 1.3331591117773964) THEN 5 ELSE 6 END ELSE CASE WHEN (`ADS`.`Feature_66` <= 0.24531311928819535) THEN 7 ELSE 8 END END ELSE 2 END AS node_id_2 
FROM `BinaryClass_100` AS `ADS`), 
`DT_node_data_15` AS 
(SELECT `Values`.nid AS nid, `Values`.`P_0` AS `P_0`, `Values`.`P_1` AS `P_1`, `Values`.`D` AS `D`, `Values`.`DP` AS `DP` 
FROM (SELECT 2 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 5 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP` UNION ALL SELECT 6 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 7 AS nid, 0.0 AS `P_0`, 1.0 AS `P_1`, 1 AS `D`, 1.0 AS `DP` UNION ALL SELECT 8 AS nid, 1.0 AS `P_0`, 0.0 AS `P_1`, 0 AS `D`, 1.0 AS `DP`) AS `Values`), 
`DT_Output_15` AS 
(SELECT `DT_node_lookup_15`.`KEY` AS `KEY`, `DT_node_lookup_15`.node_id_2 AS node_id_2, `DT_node_data_15`.nid AS nid, `DT_node_data_15`.`P_0` AS `P_0`, `DT_node_data_15`.`P_1` AS `P_1`, `DT_node_data_15`.`D` AS `D`, `DT_node_data_15`.`DP` AS `DP` 
FROM `DT_node_lookup_15` LEFT OUTER JOIN `DT_node_data_15` ON `DT_node_lookup_15`.node_id_2 = `DT_node_data_15`.nid), 
`RF_Model_15` AS 
(SELECT `DT_Output_15`.`KEY` AS `KEY`, NULL AS `Score_0`, `DT_Output_15`.`P_0` AS `Proba_0`, CASE WHEN (`DT_Output_15`.`P_0` IS NULL OR `DT_Output_15`.`P_0` > 0.0) THEN ln(`DT_Output_15`.`P_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, NULL AS `Score_1`, `DT_Output_15`.`P_1` AS `Proba_1`, CASE WHEN (`DT_Output_15`.`P_1` IS NULL OR `DT_Output_15`.`P_1` > 0.0) THEN ln(`DT_Output_15`.`P_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1` 
FROM `DT_Output_15`)
 SELECT `RF_esu_1`.`KEY`, `RF_esu_1`.`Score_0`, `RF_esu_1`.`Proba_0`, `RF_esu_1`.`LogProba_0`, `RF_esu_1`.`Score_1`, `RF_esu_1`.`Proba_1`, `RF_esu_1`.`LogProba_1` 
FROM (SELECT `RF_Model_10`.`KEY` AS `KEY`, CAST(`RF_Model_10`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_10`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_10`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_10`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_10`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_10`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_10` UNION ALL SELECT `RF_Model_11`.`KEY` AS `KEY`, CAST(`RF_Model_11`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_11`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_11`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_11`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_11`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_11`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_11` UNION ALL SELECT `RF_Model_12`.`KEY` AS `KEY`, CAST(`RF_Model_12`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_12`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_12`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_12`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_12`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_12`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_12` UNION ALL SELECT `RF_Model_13`.`KEY` AS `KEY`, CAST(`RF_Model_13`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_13`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_13`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_13`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_13`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_13`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_13` UNION ALL SELECT `RF_Model_14`.`KEY` AS `KEY`, CAST(`RF_Model_14`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_14`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_14`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_14`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_14`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_14`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_14` UNION ALL SELECT `RF_Model_15`.`KEY` AS `KEY`, CAST(`RF_Model_15`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_Model_15`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_Model_15`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_Model_15`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_Model_15`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_Model_15`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_Model_15`) AS `RF_esu_1`), 
`RF` AS 
(SELECT `RFbig_esu`.`KEY` AS `KEY`, `RFbig_esu`.`Score_0` AS `Score_0`, `RFbig_esu`.`Proba_0` AS `Proba_0`, `RFbig_esu`.`LogProba_0` AS `LogProba_0`, `RFbig_esu`.`Score_1` AS `Score_1`, `RFbig_esu`.`Proba_1` AS `Proba_1`, `RFbig_esu`.`LogProba_1` AS `LogProba_1` 
FROM (SELECT `RF_0`.`KEY` AS `KEY`, CAST(`RF_0`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_0`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_0`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_0`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_0`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_0`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_0` UNION ALL SELECT `RF_1`.`KEY` AS `KEY`, CAST(`RF_1`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`RF_1`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`RF_1`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`RF_1`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`RF_1`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`RF_1`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM `RF_1`) AS `RFbig_esu`), 
`RF_avg` AS 
(SELECT `T`.`KEY` AS `KEY`, CAST(`T`.`Score_0` AS DOUBLE) AS `Score_0`, CAST(`T`.`Proba_0` AS DOUBLE) AS `Proba_0`, CAST(`T`.`LogProba_0` AS DOUBLE) AS `LogProba_0`, CAST(`T`.`Score_1` AS DOUBLE) AS `Score_1`, CAST(`T`.`Proba_1` AS DOUBLE) AS `Proba_1`, CAST(`T`.`LogProba_1` AS DOUBLE) AS `LogProba_1` 
FROM (SELECT `RF`.`KEY` AS `KEY`, avg(CAST(`RF`.`Score_0` AS DOUBLE)) AS `Score_0`, avg(CAST(`RF`.`Proba_0` AS DOUBLE)) AS `Proba_0`, NULL AS `LogProba_0`, avg(CAST(`RF`.`Score_1` AS DOUBLE)) AS `Score_1`, avg(CAST(`RF`.`Proba_1` AS DOUBLE)) AS `Proba_1`, NULL AS `LogProba_1` 
FROM `RF` GROUP BY `RF`.`KEY`) AS `T`), 
orig_cte AS 
(SELECT `RF_avg`.`KEY` AS `KEY`, `RF_avg`.`Score_0` AS `Score_0`, `RF_avg`.`Score_1` AS `Score_1`, `RF_avg`.`Proba_0` AS `Proba_0`, `RF_avg`.`Proba_1` AS `Proba_1`, `RF_avg`.`LogProba_0` AS `LogProba_0`, `RF_avg`.`LogProba_1` AS `LogProba_1`, CAST(NULL AS SIGNED INTEGER) AS `Decision`, NULL AS `DecisionProba` 
FROM `RF_avg`), 
score_class_union AS 
(SELECT scu.`KEY_u` AS `KEY_u`, scu.class AS class, scu.`LogProba` AS `LogProba`, scu.`Proba` AS `Proba`, scu.`Score` AS `Score` 
FROM (SELECT orig_cte.`KEY` AS `KEY_u`, 0 AS class, orig_cte.`LogProba_0` AS `LogProba`, orig_cte.`Proba_0` AS `Proba`, orig_cte.`Score_0` AS `Score` 
FROM orig_cte UNION ALL SELECT orig_cte.`KEY` AS `KEY_u`, 1 AS class, orig_cte.`LogProba_1` AS `LogProba`, orig_cte.`Proba_1` AS `Proba`, orig_cte.`Score_1` AS `Score` 
FROM orig_cte) AS scu), 
score_max AS 
(SELECT orig_cte.`KEY` AS `KEY`, orig_cte.`Score_0` AS `Score_0`, orig_cte.`Score_1` AS `Score_1`, orig_cte.`Proba_0` AS `Proba_0`, orig_cte.`Proba_1` AS `Proba_1`, orig_cte.`LogProba_0` AS `LogProba_0`, orig_cte.`LogProba_1` AS `LogProba_1`, orig_cte.`Decision` AS `Decision`, orig_cte.`DecisionProba` AS `DecisionProba`, max_select.`KEY_m` AS `KEY_m`, max_select.`max_Proba` AS `max_Proba` 
FROM orig_cte LEFT OUTER JOIN (SELECT score_class_union.`KEY_u` AS `KEY_m`, max(score_class_union.`Proba`) AS `max_Proba` 
FROM score_class_union GROUP BY score_class_union.`KEY_u`) AS max_select ON orig_cte.`KEY` = max_select.`KEY_m`), 
union_with_max AS 
(SELECT score_class_union.`KEY_u` AS `KEY_u`, score_class_union.class AS class, score_class_union.`LogProba` AS `LogProba`, score_class_union.`Proba` AS `Proba`, score_class_union.`Score` AS `Score`, score_max.`KEY` AS `KEY`, score_max.`Score_0` AS `Score_0`, score_max.`Score_1` AS `Score_1`, score_max.`Proba_0` AS `Proba_0`, score_max.`Proba_1` AS `Proba_1`, score_max.`LogProba_0` AS `LogProba_0`, score_max.`LogProba_1` AS `LogProba_1`, score_max.`Decision` AS `Decision`, score_max.`DecisionProba` AS `DecisionProba`, score_max.`KEY_m` AS `KEY_m`, score_max.`max_Proba` AS `max_Proba` 
FROM score_class_union LEFT OUTER JOIN score_max ON score_class_union.`KEY_u` = score_max.`KEY`), 
arg_max_cte AS 
(SELECT score_max.`KEY` AS `KEY`, score_max.`Score_0` AS `Score_0`, score_max.`Score_1` AS `Score_1`, score_max.`Proba_0` AS `Proba_0`, score_max.`Proba_1` AS `Proba_1`, score_max.`LogProba_0` AS `LogProba_0`, score_max.`LogProba_1` AS `LogProba_1`, score_max.`Decision` AS `Decision`, score_max.`DecisionProba` AS `DecisionProba`, score_max.`KEY_m` AS `KEY_m`, score_max.`max_Proba` AS `max_Proba`, `arg_max_t_Proba`.`KEY_Proba` AS `KEY_Proba`, `arg_max_t_Proba`.`arg_max_Proba` AS `arg_max_Proba` 
FROM score_max LEFT OUTER JOIN (SELECT union_with_max.`KEY` AS `KEY_Proba`, max(union_with_max.class) AS `arg_max_Proba` 
FROM union_with_max 
WHERE union_with_max.`max_Proba` <= union_with_max.`Proba` GROUP BY union_with_max.`KEY`) AS `arg_max_t_Proba` ON score_max.`KEY` = `arg_max_t_Proba`.`KEY_Proba`)
 SELECT arg_max_cte.`KEY` AS `KEY`, arg_max_cte.`Score_0` AS `Score_0`, arg_max_cte.`Score_1` AS `Score_1`, arg_max_cte.`Proba_0` AS `Proba_0`, arg_max_cte.`Proba_1` AS `Proba_1`, CASE WHEN (arg_max_cte.`Proba_0` IS NULL OR arg_max_cte.`Proba_0` > 0.0) THEN ln(arg_max_cte.`Proba_0`) ELSE -1.79769313486231e+308 END AS `LogProba_0`, CASE WHEN (arg_max_cte.`Proba_1` IS NULL OR arg_max_cte.`Proba_1` > 0.0) THEN ln(arg_max_cte.`Proba_1`) ELSE -1.79769313486231e+308 END AS `LogProba_1`, arg_max_cte.`arg_max_Proba` AS `Decision`, arg_max_cte.`max_Proba` AS `DecisionProba` 
FROM arg_max_cte