-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretRegressor_glmnet
-- Dataset : freidman1
-- Database : mssql


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH linear_input AS 
(SELECT [ADS].[KEY] AS [KEY], CAST([ADS].[Feature_0] AS FLOAT(53)) AS [Feature_0], CAST([ADS].[Feature_1] AS FLOAT(53)) AS [Feature_1], CAST([ADS].[Feature_2] AS FLOAT(53)) AS [Feature_2], CAST([ADS].[Feature_3] AS FLOAT(53)) AS [Feature_3], CAST([ADS].[Feature_4] AS FLOAT(53)) AS [Feature_4], CAST([ADS].[Feature_5] AS FLOAT(53)) AS [Feature_5], CAST([ADS].[Feature_6] AS FLOAT(53)) AS [Feature_6], CAST([ADS].[Feature_7] AS FLOAT(53)) AS [Feature_7], CAST([ADS].[Feature_8] AS FLOAT(53)) AS [Feature_8], CAST([ADS].[Feature_9] AS FLOAT(53)) AS [Feature_9] 
FROM freidman1 AS [ADS]), 
linear_model_cte AS 
(SELECT linear_input.[KEY] AS [KEY], 5.0091865660752335 * linear_input.[Feature_0] + 10.183506868155924 * linear_input.[Feature_1] + -0.06865442996963501 * linear_input.[Feature_2] + 9.201068727976583 * linear_input.[Feature_3] + 5.254697126310205 * linear_input.[Feature_4] + 0.0 * linear_input.[Feature_5] + -0.18608823790717993 * linear_input.[Feature_6] + 0.5771422134159871 * linear_input.[Feature_7] + 0.0 * linear_input.[Feature_8] + -0.8893343510317618 * linear_input.[Feature_9] + 0.7987359748117318 AS [Estimator] 
FROM linear_input)
 SELECT linear_model_cte.[KEY] AS [KEY], linear_model_cte.[Estimator] AS [Estimator] 
FROM linear_model_cte