-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretRegressor_glmnet
-- Dataset : boston
-- Database : db2


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH linear_input AS 
(SELECT "ADS"."KEY" AS "KEY", CAST("ADS"."Feature_0" AS DOUBLE) AS "Feature_0", CAST("ADS"."Feature_1" AS DOUBLE) AS "Feature_1", CAST("ADS"."Feature_2" AS DOUBLE) AS "Feature_2", CAST("ADS"."Feature_3" AS DOUBLE) AS "Feature_3", CAST("ADS"."Feature_4" AS DOUBLE) AS "Feature_4", CAST("ADS"."Feature_5" AS DOUBLE) AS "Feature_5", CAST("ADS"."Feature_6" AS DOUBLE) AS "Feature_6", CAST("ADS"."Feature_7" AS DOUBLE) AS "Feature_7", CAST("ADS"."Feature_8" AS DOUBLE) AS "Feature_8", CAST("ADS"."Feature_9" AS DOUBLE) AS "Feature_9", CAST("ADS"."Feature_10" AS DOUBLE) AS "Feature_10", CAST("ADS"."Feature_11" AS DOUBLE) AS "Feature_11", CAST("ADS"."Feature_12" AS DOUBLE) AS "Feature_12" 
FROM "BOSTON" AS "ADS"), 
linear_model_cte AS 
(SELECT linear_input."KEY" AS "KEY", -0.05267969151430771 * linear_input."Feature_0" + 0.01685020698704766 * linear_input."Feature_1" + -0.03774406584878643 * linear_input."Feature_2" + 2.3781295650793983 * linear_input."Feature_3" + -7.063548561670039 * linear_input."Feature_4" + 4.644895382055689 * linear_input."Feature_5" + -0.011634644483086723 * linear_input."Feature_6" + -0.720894257370521 * linear_input."Feature_7" + 0.033045621214373766 * linear_input."Feature_8" + -0.0025389373269056967 * linear_input."Feature_9" + -0.8287116840054966 * linear_input."Feature_10" + 0.008408154916369249 * linear_input."Feature_11" + -0.36972527128894284 * linear_input."Feature_12" + 18.62107488584135 AS "Estimator" 
FROM linear_input)
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte