-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : CaretRegressor_ctree
-- Dataset : freidman2
-- Database : oracle


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH "DT_node_lookup" AS 
(SELECT "ADS"."KEY" AS "KEY", CASE WHEN ("ADS"."Feature_2" <= 0.533834716928) THEN CASE WHEN ("ADS"."Feature_2" <= 0.239951225246) THEN 3 ELSE 4 END ELSE CASE WHEN ("ADS"."Feature_1" <= 946.908088385865) THEN CASE WHEN ("ADS"."Feature_1" <= 524.008947806149) THEN 7 ELSE 8 END ELSE CASE WHEN ("ADS"."Feature_2" <= 0.804009709038) THEN 10 ELSE 11 END END END AS node_id_2 
FROM "FREIDMAN2" "ADS"), 
"DT_node_data" AS 
(SELECT "Values".nid AS nid, "Values"."E" AS "E" 
FROM (SELECT 3 AS nid, 116.101510330848 AS "E" FROM DUAL UNION ALL SELECT 4 AS nid, 344.083129480566 AS "E" FROM DUAL UNION ALL SELECT 7 AS nid, 229.239049608902 AS "E" FROM DUAL UNION ALL SELECT 8 AS nid, 598.700031943516 AS "E" FROM DUAL UNION ALL SELECT 10 AS nid, 860.233522230294 AS "E" FROM DUAL UNION ALL SELECT 11 AS nid, 1172.48937975921 AS "E" FROM DUAL) "Values"), 
"DT_Output" AS 
(SELECT "DT_node_lookup"."KEY" AS "KEY", "DT_node_lookup".node_id_2 AS node_id_2, "DT_node_data".nid AS nid, "DT_node_data"."E" AS "E" 
FROM "DT_node_lookup" LEFT OUTER JOIN "DT_node_data" ON "DT_node_lookup".node_id_2 = "DT_node_data".nid)
 SELECT "DT_Output"."KEY" AS "KEY", "DT_Output"."E" AS "Estimator" 
FROM "DT_Output"